monicahq/monica

- resources/views/people/debt/index.blade.php
Should fix https://github.com/monicahq/monica/issues/84
> use correct translation if you're owed some debt

- CONTRIBUTING.md
Fixes issue #67 so all links in `CONTRIBUTING.md` are fixed.
> Issue #67: Fixes 404 links in CONTRIBUTING.md

- resources/views/layouts/skeleton.blade.php
> Do not output GA and Intercom scripts if no keys are set (#74)

- composer.lock
- database/migrations/2017_06_07_173437_add_multiple_genders_choices.php
- resources/lang/en/app.php
- resources/lang/en/people.php
- resources/lang/fr/app.php
- resources/lang/fr/people.php
- resources/views/people/create.blade.php
- resources/views/people/dashboard/edit.blade.php
- resources/views/people/dashboard/kids/add.blade.php
- resources/views/people/dashboard/kids/edit.blade.php
- resources/views/people/dashboard/significantother/add.blade.php
- resources/views/people/dashboard/significantother/edit.blade.php
People have complained that they want to add more genders than Male/Female. It makes sense. The quick workaround for this is to add a `rather not say` choice everywhere we mention the gender for people, which would be selected by default. In the future we'll be able to add more genders if needed.
This fixes #44
> Add `Rather not say` gender

- resources/lang/fr/auth.php
Used Google Translate for the translation so please update if they're a bit odd.
> Add missing items

- app/Contact.php
Removes the n+1 problem when calling getLastUpdated() on a contact in the contacts collection in resources/views/people/index.blade.php
> remove n+1 problem when getting a users timezone for multiple contacts

- app/Http/ViewComposers/CountrySelectViewComposer.php
- app/Providers/AppServiceProvider.php
- resources/views/partials/components/country-select.blade.php
- resources/views/people/dashboard/edit.blade.php
I've added a fix for the alphabetic country list, and externalised the country dropdown to a component. This component is powered by a View composer which means that no data tie up is needed in the main controller..Just plonk the include file in the right place and tell it what it should bind to and away you go. There may be other parts of the project that could benefit from using this component now it is in place.
> 110 fix for alphabetic country list on profile edit

- app/Exceptions/Handler.php
- app/Http/routes.php
I've named the route for this just to make the code a bit more readable. I think the problem is due to sessions expiring prior to people submitting the form and thus the token on the other side is dead causing the exception.
> 141 token mismatch issues

- app/Console/Commands/SendNotifications.php
- app/Jobs/SendReminderEmail.php
- app/Jobs/SetNextReminderDate.php
This is an attempt to fix #172
> Fix reminders not being sent or sent too often

- app/Http/Controllers/DashboardController.php
In dashboard the gift count displayed was incorrect. The issue has been fixed
> Fixed gifts count issue in dashboard

- resources/views/people/dashboard/people-information/index.blade.php
> Fix a typo in the dashboard

- resources/views/people/dashboard/people-information/index.blade.php
If merged this will close #77.
> Change the phone number text to be a tel link

- database/migrations/2017_06_14_132911_add_zar_currency_to_currencies_table.php
> Add South African (ZAR) currency

- resources/lang/en/app.php
- resources/lang/fr/app.php
- resources/lang/pt-br/app.php
- resources/lang/ru/app.php
- resources/views/partials/footer.blade.php
> Add a link to the source code on GitHub in the footer

- app/Http/Controllers/PeopleController.php
- resources/lang/en/people.php
- resources/lang/fr/people.php
- resources/lang/pt-br/people.php
- resources/lang/ru/people.php
> Add reminder when setting a contact birthday

- app/Console/Commands/ImportCSV.php
You can use user emails now.
The validity of path and user will also be checked.
> Small refactor of CSV importing

- docs/installation/debian.md
I extended the apache configuration to match what is described in the
laravel documentation.
> remove some old sections and extend the apache configuration

- CHANGELOG
- resources/views/people/edit.blade.php
> Fix address fields order

- .gitignore
- resources/views/emails/reminder/reminder.blade.php
There was an error introduced in the reminder email.
> Fix reminder email

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG
- config/monica.php
- resources/lang/en/app.php
- resources/lang/fr/app.php
- resources/lang/pt-br/app.php
- resources/lang/ru/app.php
- resources/views/partials/footer.blade.php
Yes. Versioning is coming to Monica.
> Add notion of versions

- app/Http/Controllers/DashboardController.php
Fixes bug in latest actions that was causing contact_complete_name to return null.
> fix bug in latest actions

- resources/lang/en/settings.php
- resources/lang/fr/settings.php
- resources/lang/pt-br/settings.php
- resources/lang/ru/settings.php
> Fix Google Contact instructions link

- .env.example
- app/Console/Commands/SendNotifications.php
- app/Http/Controllers/People/RemindersController.php
- config/app.php
> Fix reminder emails not respecting timezones

- app/Console/Commands/SendNotifications.php
There is a bug that I introduced with the last merge. I need to rollback and fix it properly tomorrow.
> Rollback #469

- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
Fix #479 
- [ *] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [ *] If the PR is related to an issue or fix one, don't forget to indicate it.
- [ *] Make sure that the change you propose is the smallest possible.
> Fix for Issue 479

- CHANGELOG
- database/migrations/2017_07_18_215312_add_danish_kroner_to_currencies_table.php
> Add Danish krone

- CHANGELOG
- database/migrations/2017_07_18_215758_add_indian_rupee_to_currencies_table.php
> Add Indian rupee currency

- resources/views/people/gifts/add.blade.php
> Fix gift view not showing

- .env.example
- app/Exceptions/Handler.php
- composer.json
- composer.lock
- config/app.php
- config/monica.php
- config/sentry.php
> Add Sentry to production environment

- CHANGELOG
- CONTRIBUTORS
- database/migrations/2017_08_02_124102_add_world_currencies.json
- database/migrations/2017_08_02_124102_add_world_currencies.php
This pull request adds in a list of world currencies based off of [world-currencies](https://github.com/wiredmax/world-currencies)
Closes #339
> Add world currency list

- resources/lang/en/app.php
This was slightly confusing to me as a first-time user, since I had just seen the "blog" link from the main site. Hopefully this small changes makes it more explicit what the link is about without having to click it :)
Note: I struck out the entries from the checklist that didn't apply to this change, rather than mark them done or removing them.
> footer: clarify that newsletter is sent by email

- app/Contact.php
- app/Gift.php
- app/Http/Controllers/People/KidsController.php
> fix kid deletion problem

- resources/views/people/dashboard/kids/add.blade.php
> Fix wording

- CHANGELOG
- app/Contact.php
Fix #540 
Sort contacts by First Name, Last name.
> 540 list contacts first last

- resources/lang/cz/app.php
- resources/lang/cz/passwords.php
- resources/lang/cz/people.php
- resources/lang/cz/settings.php
> Czech translation updated

- CHANGELOG
- CONTRIBUTORS
- app/Jobs/AddContactFromVCard.php
Fixes https://github.com/monicahq/monica/issues/555
**Should be passed these arguments**
**Was being passed these arguments**
---
> Birthday reminders bug

- CHANGELOG
- CONTRIBUTORS
- resources/views/people/dashboard/kids/add.blade.php
> Typo with adding no existing contact view

- readme.md
None of the checklist items really apply. Just a readme typo.
> Fix contribute typo in readme

- resources/lang/de/dashboard.php
- resources/lang/de/people.php
- resources/lang/de/settings.php
- [x ] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x ] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x ] Make sure that the change you propose is the smallest possible.
- [x ] Screenshots are included if the PR changes the UI.
- [x ] Tests added for this feature/bug.
- [x ] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [x ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [x ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.
> #525 improve german

- docs/installation/generic.md
This was a bit confusing for some users.
> Add more details about queues and sync

- resources/lang/de/people.php
Just a small PR for some missing translations I've noticed. I might do another one if I find more 😉
> Add missing significant other translations for german

- CONTRIBUTING.md
> Fix link to test suit setup in CONTRIBUTING.md

- CHANGELOG
- app/Http/Requests/SettingsRequest.php
Added validation when changing your email adress to ensure the email is unique. Fixes #684.
> Add validation when changing email #684

- docs/installation/vagrant.md
I have added a single documentation file to explain how to create a VM running Monica using Vagrant, to have an even quicker installation method, using the Vagrant file and provisioning script I have created.
> Added vagrant installation instructions as per issue #30

- routes/web.php
Reverts monicahq/monica#730
What I committed doesn't match the documentation or the title of the PR. I'm not sure how I screwed that up.
> Revert "Fix the URL::forceSchema to forceScheme"

- .travis.yml
- readme.md
It's good practice to monitor the % of code coverage, and we should aim to have as much as possible.
> Add Codecov for code coverage

- app/Jobs/AddContactFromVCard.php
> Fix contact field types not being linked to account during vcard import

- resources/lang/cz/people.php
- resources/lang/de/people.php
- resources/lang/en/people.php
- resources/lang/fr/people.php
- resources/lang/it/people.php
- resources/lang/pt-br/people.php
- resources/lang/ru/people.php
Fix #857 
The message people.gifts_update_success was missing.
> Add gifts_update_success

- CHANGELOG
Update with my recent changes.
Remove double "RELEASED VERSIONS" messages.
> Update changelog with recent changes

- app.json
- app/Console/Commands/SetupProduction.php
- config/database.php
- docs/installation/heroku.md
This will close #705
When running setup:production, a new account is created with " admin@admin.com / admin " credentials.
I had to fix mysql connection to "strict=false" because of #781 ...
> Fix heroku deploy

- app/Helpers/SearchHelper.php
- app/Http/Controllers/Api/ApiContactController.php
- app/Http/Controllers/Api/ApiController.php
- app/Traits/Searchable.php
- config/api.php
- tests/Api/ApiControllerTest.php
- tests/Helper/SearchHelperTest.php
- tests/Unit/Traits/SearchableTest.php
> Add sort capabilities in the API

- app/Http/Controllers/ContactsController.php
Search was broken due to a change in the Searchable trait.
> Fix broken search

- CHANGELOG
- app/Account.php
- app/Http/Controllers/SettingsController.php
This fixes https://github.com/monicahq/monica/issues/922
> Fix reset account deleting default account values

- resources/views/settings/export.blade.php
> Update SQL Import instructions link

- database/seeds/FakeContentTableSeeder.php
`php artisan setup:test` is broken because of #984
> Fix Faker trait use

- app/Traits/VCardImporter.php
Fix this issue https://sonarcloud.io/project/issues?id=monica&issues=AWIzelSnvUrXx_rKYUW-&open=AWIzelSnvUrXx_rKYUW-
> Fix sonar bug

- app/Http/Controllers/Api/ApiContactController.php
- app/Http/Controllers/Api/ApiContactFieldController.php
Fiw bugs introduced in #992.
Thanks to @muglug - see https://github.com/monicahq/monica/pull/973#issuecomment-373966557
> Fix bug with return values

- config/app.php
- resources/views/people/debt/index.blade.php
> Remove MoneyHelper from aliases

- app/Http/Controllers/Api/ApiActivityController.php
- app/Http/Controllers/Api/ApiCallController.php
- app/Http/Controllers/Api/ApiController.php
- app/Http/Controllers/Api/ApiDebtController.php
- app/Http/Controllers/Api/ApiGiftController.php
- app/Http/Controllers/Api/ApiJournalController.php
- app/Http/Controllers/Api/ApiNoteController.php
- app/Http/Controllers/Api/ApiReminderController.php
- app/Http/Controllers/Api/ApiTagController.php
This PR will address https://github.com/monicahq/chandler/issues/95
> Add sorting capabilities to most models in the API

- CHANGELOG
- app/Http/Resources/Contact/Contact.php
This should address https://github.com/monicahq/chandler/issues/136
> Add linkedin url in the Contact object returned by the API

- app/Contact.php
- app/Http/Controllers/Api/ApiContactController.php
- app/Http/Controllers/Api/ApiController.php
- app/Http/Resources/Contact/ContactWithContactFields.php
- app/Http/Resources/ContactField/ContactFieldCollection.php
- tests/Api/ApiControllerTest.php
This will address https://github.com/monicahq/chandler/issues/137
> Add with parameter in Contact object to retrieve contact fields

- tests/Api/Contact/ApiContactControllerTest.php
- tests/Helper/DateHelperTest.php
- tests/Helper/VCardHelperTest.php
> Use assertCount

- .env.example
- config/monica.php
- resources/views/layouts/skeleton.blade.php
Fuck user tracking by corporations, hooray to privacy.
> Remove the ability to track users through Google Analytics and Intercom

- database/migrations/2018_04_14_081052_fix_wrong_gender.php
This closes #https://github.com/monicahq/monica/issues/1169
> Fix gender id set to 0

- CHANGELOG
- resources/views/people/dashboard/index.blade.php
> Fix how you meet section not being shown

- resources/views/people/edit.blade.php
> Fix firstname not being filled when editing a contact

- app/Console/Commands/Update.php
> Fix cache clear in monica:update command

- .styleci.yml
- app/Console/Commands/Update.php
- app/Contact.php
- app/Http/Controllers/Settings/ReminderRulesController.php
- app/Http/Resources/Country/Country.php
- app/ImportJob.php
- app/Notification.php
- database/factories/ModelFactory.php
- database/migrations/2018_05_06_194710_delete_reminder_sent_table.php
- database/seeds/CountriesSeederTable.php
- tests/Api/ApiAdressesTest.php
- tests/Unit/AccountTest.php
- tests/Unit/CountriesTest.php
- tests/Unit/Jobs/SendNotificationEmailTest.php
- tests/Unit/Jobs/SendNotificationsTest.php
monica:update command can bu used with:
`php artisan monica:update --composer-install --dev` with dev composer packages
`php artisan monica:update --composer-install` without  dev composer packages
> Fix update command

- app/Helpers/SearchHelper.php
- app/Helpers/StringHelper.php
It might be related to https://github.com/monicahq/chandler/issues/164
> Fix select like

- tests/Api/ApiAdressesTest.php
This follow comment here: https://github.com/monicahq/monica/pull/1292#discussion_r187802050
> Remove id from Address tests

- CHANGELOG
- database/migrations/2018_05_13_110706_add_ex_wife_husband_relationship.php
- resources/lang/en/app.php
This adds the feature request #1303.
> Add ex wife/husband as a relationship (#1303)

- app/Helpers/DateHelper.php
- database/migrations/2018_05_24_160546_fix-inconsistant-reminder-time.php
- tests/Helper/DateHelperTest.php
Fix a bug I've introduced in #1113
> Fix inconsistent reminder_time values

- resources/lang/vendor/confirmation/en/confirmation.php
> Fix text for email confirmation alert

- crowdin.yml
Update crowdin configuration to set confirmation file path
> Update crowdin configuration

- config/monica.php
> Fix default value for double optin on signup

- resources/lang/vendor/confirmation/en/confirmation.php
- resources/views/auth/login.blade.php
Url added in the translation in #1414 should not be here
> Fix url confirmation email in i18n

- .env.example
This closes https://github.com/monicahq/monica/issues/1446
> Change link to timezones in env.example

- database/seeds/FakeContentTableSeeder.php
First, I'm new to contributing to open source and to Laravel, so go easy 😸 I'm more experienced with front-end too, so most of my contributions won't be on the back-end. I'm excited about this project, I think it's awesome what you guys are doing!
This is my attempt at fixing #1433. I'm not sure if this is the most clean / efficient way of implementing - please let me know any suggestions!
> Fix for default accounts email confirmation in setup:test

- CHANGELOG
- app/Models/Contact/Contact.php
- app/Models/User/User.php
- resources/views/people/create.blade.php
- resources/views/people/edit.blade.php
- resources/views/people/missing.blade.php
- resources/views/people/relationship/edit.blade.php
- resources/views/people/relationship/new.blade.php
- tests/Unit/UserTest.php
This will fix https://github.com/monicahq/monica/issues/1493
> Fix bugs related to contact edition

- routes/web.php
> Fix people.food.update route

- database/seeds/FakeContentTableSeeder.php
Related to https://github.com/monicahq/monica/commit/a95d0f33684fc419bf142dd37edbaf640c408609#r29832189
> Fix seeder datetime use

- database/migrations/2018_07_08_104306_update-timestamps-timezone.php
> Fix update timestamps migration

- CHANGELOG
- app/Http/Controllers/SettingsController.php
- resources/views/settings/subscriptions/account.blade.php
> Fix a bunch of bugs

- CHANGELOG
- app/Models/Contact/Contact.php
> feat: add ability to search contacts by job

- CHANGELOG
- app/Http/Kernel.php
Add TrimStrings middleware, as documented [here](https://laravel.com/docs/5.6/requests#input-trimming-and-normalization)
> Add TrimStrings middleware

- tests/Helper/DateHelperTest.php
> Add test for DateHelper::getFullMonthAndDate

- docs/contribute/index.md
Will close https://github.com/monicahq/monica/issues/1605
> docs: add instruction about conventional commit message

- resources/views/marketing/auth.blade.php
- resources/views/marketing/skeleton.blade.php
> fix: fix css load instruction

- CHANGELOG
- app/Helpers/SearchHelper.php
- app/Traits/Searchable.php
- tests/Unit/Helpers/SearchHelperTest.php
Fix search with a search field that not exists
> fix: fix search with wrong search field

- docs/installation/cloudron.md
- docs/installation/index.md
> docs: add cloudron as installation method

- docs/installation/heroku.md
> docs: remove wrong no-cron limitation and fix image link

- app/Console/Commands/OneTime/MoveAvatars.php
Fix moveavatars command because I forgot one = character :(
> fix: fix moveavatars command for 'storage' parameter

- app/Http/Controllers/SettingsController.php
- app/Jobs/ExportAccountAsSQL.php
Use public storage to store the file, instead of default filesystem.
See https://sentry.io/share/issue/d6bdda8e04204e759626b84950515b82/
Fixes PRODUCTION-APP-79
> fix: fix sql export 

- resources/views/errors/500.blade.php
> fix: test if user is authenticated on error 500 page

- CHANGELOG
- app/Exceptions/Handler.php
> fix: stop reporting oauth exceptions

- app/Http/Controllers/ContactsController.php
- database/migrations/2018_10_01_211757_add_number_of_views.php
- tests/Feature/ContactTest.php
This will let us show the contacts the user has the most viewed in his account.
>  feat: count the number of times a contact is seen

- app/Models/Account/Account.php
- app/Services/Auth/Population/PopulateModulesTable.php
- tests/Unit/Models/AccountTest.php
- tests/Unit/Services/Auth/PopulateModulesTableTest.php
This changes how we populate the default modules table, so it's cleaner and more robust too.
> feat: change how default module table is populated

- CHANGELOG
- resources/views/people/index.blade.php
- This is related to #1903 
- Readd lines of changelog removed with #1916
> fix: fix a message that don't need trans_choice

- app/Models/Account/Account.php
> fix: fix undefined offset on subscription

- resources/views/people/index.blade.php
Fix #1957 did not target the right messages!
> fix: fix the right messages that don't need trans_choice

- composer.lock
> chore(deps): update dependencies

- resources/views/people/introductions/index.blade.php
Fix the 'Met through person' link in case the person is identified.
This fix #2003
> fix: fix the 'met through' link

- routes/web.php
> fix: fix conversations route

- CHANGELOG
- resources/views/people/work/edit.blade.php
Fix https://github.com/monicahq/monica/issues/2026
> fix: fix work information not being able to be edited

- app/Models/CardDAV/Backends/MonicaPrincipleBackend.php
- public/.htaccess
don't redirect trailing slashes url for carddav
> fix: fix carddav url handle

- CHANGELOG
- resources/views/people/relationship/edit.blade.php
> fix: fix editing relationship not working

- CHANGELOG
- resources/views/activities/form.blade.php
> feat: remove limitation on date when creating an activity

- app/Services/Instance/Geolocalization/GetGPSCoordinate.php
- config/location.php
Improve https://locationiq.com/ call
> chore: improve locationiq search url

- CHANGELOG
- app/Providers/RouteServiceProvider.php
> fix: fix exception when user is logged out

- CHANGELOG
- app/Models/Account/Account.php
> fix: fix subscription plan display

- CHANGELOG
- app/Http/Controllers/DashboardController.php
> fix: fix dashboard calls display

- CHANGELOG
- app/Http/Controllers/Contacts/TagsController.php
> fix: fix associate null tags

- CHANGELOG
- app/Models/CardDAV/Backends/MonicaPrincipalBackend.php
- tests/Api/Carddav/CarddavServerTest.php
> fix: fix carddav group-member-set propfind call

- CHANGELOG
- resources/views/people/_header.blade.php
> fix: fix contacts view in case of birthdate returns null

- resources/views/people/_header.blade.php
- resources/views/settings/personalization/index.blade.php
This should fix all the errors leading to premium features unusable on the open source version.
> fix: fix wrong passing of booleans disabling premium features

- CHANGELOG
- app/Http/Controllers/Api/ApiContactTagController.php
- tests/Api/Contact/ApiContactTagControllerTest.php
> fix: fix settags api call with an empty tag

- CHANGELOG
- app/Http/Controllers/Api/Account/ApiGenderController.php
- app/Http/Resources/Gender/Gender.php
- app/Http/Resources/Gender/GenderCollection.php
- app/Services/Account/Gender/CreateGender.php
- app/Services/Account/Gender/DestroyGender.php
- app/Services/Account/Gender/UpdateGender.php
- routes/api.php
- tests/Api/Account/ApiGenderControllerTest.php
- tests/Unit/Services/Account/Gender/CreateGenderTest.php
- tests/Unit/Services/Account/Gender/DestroyGenderTest.php
- tests/Unit/Services/Account/Gender/UpdateGenderTest.php
Fix https://github.com/monicahq/monica/issues/1951
> feat: add api methods to manage genders

- CHANGELOG
- app/Http/Controllers/SettingsController.php
- database/migrations/2019_01_06_135133_update_u2f_key_table.php
> fix: fix ability to delete a user with a u2f key activated

- CHANGELOG
- app/Helpers/DateHelper.php
- app/Helpers/MoneyHelper.php
- app/Helpers/SearchHelper.php
- app/Models/ModelBinding.php
- app/Models/ModelBindingWithContact.php
> fix: fix model binding when it is a guest request

- CHANGELOG
- app/Services/VCard/ImportVCard.php
- tests/Unit/Services/VCard/ImportVCardTest.php
> fix: fix VCard import with partial N entry

- CHANGELOG
- resources/views/people/edit.blade.php
- resources/views/people/relationship/edit.blade.php
> fix: fix contact edit

- app/Services/VCalendar/ExportVCalendar.php
- tests/Api/DAV/CardEtag.php
This adds the VALUE=DATE parameter to DTSTART and DTEND
> fix: dates must be set with date type in vevent (caldav)

- CHANGELOG
- app/Models/User/User.php
> fix: fix case when stay in touch trigger date is null

- CHANGELOG
- database/migrations/2019_02_08_234959_remove_users_without_account.php
Seems like it can be users in the users table with a not existing account in the accounts table ...
> fix: remove users without account in accounts table

- app/Models/Contact/Contact.php
The fix on #2391 didn't work very well, this works now
> fix: fix no timestamp update on number of views update

- CHANGELOG
- app/Http/Controllers/ActivitiesController.php
This fix #2425 and will again fix #2327
> fix: fix adding people on activity update

- CHANGELOG
- app/Models/Contact/Contact.php
- app/Services/Contact/Contact/CreateContact.php
- app/Services/Contact/Contact/DestroyContact.php
- app/Services/Contact/Contact/UpdateBirthdayInformation.php
- app/Services/Contact/Contact/UpdateContact.php
- app/Services/Contact/Contact/UpdateDeceasedInformation.php
- tests/Api/Contact/ApiContactControllerTest.php
This fix #2390
I've also removed all `$contact` services properties.
> fix: fix contact information update

- CHANGELOG
- app/Services/VCard/ExportVCard.php
- app/Services/VCard/ImportVCard.php
- tests/Unit/Services/VCard/ImportVCardTest.php
A user had a problem importing a vcard with a BDAY value like "--02-14"
> fix: fix import/export vcard with birthday with year unknown

- tests/Unit/Helpers/MoneyHelperTest.php
Test if locale formatting is working with MoneyHelper::format function
> test: add a test in MoneyHelper with locale formatting

- composer.json
- composer.lock
> chore(deps): require php 7.2

- CHANGELOG
- app/Http/Controllers/Auth/RegisterController.php
> fix: fix register request validate

- CHANGELOG
- app/Http/Controllers/SettingsController.php
> fix: fix settings/dav route

- resources/views/people/relationship/edit.blade.php
This is my first PR so hopefully I've done it right! Please let me know if I haven't.
> fix: remove braces from edit relationship page (#2635)

- Dockerfile
Fix docker creation after webauthn implentation
> fix: fix docker image creation

- composer.json
- composer.lock
composer require gmp extension
> chore: add gmp extension

- CHANGELOG
- resources/views/people/debt/form.blade.php
> fix: fix debt direction on debt edit

- package.json
- yarn.lock
this removes a jquery dependency.
> chore(deps): remove unused typeahead.js

- public/img/monica_140.svg
- public/img/monica_192.svg
- public/img/monica_512.svg
- public/manifest.webmanifest
Per #2668, I have fixed the bug with the 140px logo, and added 192px and 512px logos as independent files.
> fix: add resized logos and fix scaling

- CHANGELOG
- resources/views/people/relationship/edit.blade.php
> fix: fix relationship id with no gender

- CHANGELOG
- resources/views/people/relationship/index.blade.php
> fix: fix relationship list view

- app/Helpers/ComposerScripts.php
- phpstan.neon
> chore: fix composer scripts

- resources/views/people/index.blade.php
Resolves #2522.
My first contribution here, yay! 🎉 
I didn't find any related tests and locally the whole test suite is passing, let me know if you would like me to add something for this URL check.
Thanks,
Vlad
> fix: correct link for deceased flag in archived contacts list

- CHANGELOG.md
- app/Providers/DAVServiceProvider.php
- azure-pipelines.yml
- composer.json
- composer.lock
- docs/contribute/index.md
- docs/installation/debian.md
- docs/installation/generic.md
- docs/installation/index.md
- docs/installation/ubuntu.md
- scripts/vagrant/build/install-monica.sh
php 7.3 is required by #2868 , so upgrade to this version in this separate PR.
> chore(deps): upgrade to php7.3

- CHANGELOG.md
- app/Services/VCard/ExportVCard.php
- tests/Api/DAV/CardEtag.php
> fix: fix vcard export with empty gender

- CHANGELOG.md
- app/Http/Controllers/Auth/RegisterController.php
- app/Models/Account/Account.php
- app/Models/User/User.php
- tests/Feature/RegisterTest.php
- tests/Unit/Models/AccountTest.php
> fix: fix exception in case a user register twice

- CHANGELOG.md
- app/Http/Controllers/DashboardController.php
- app/Models/Contact/Contact.php
> fix: fix last consulted list

- CHANGELOG.md
- app/Http/Middleware/VerifyCsrfToken.php
- config/services.php
- routes/web.php
See https://laravel.com/docs/5.8/billing#handling-stripe-webhooks
> feat: add stripe webhook handle

- .github/FUNDING.yml
> chore: add support button

- resources/views/people/_header.blade.php
Fix the "This is you" message on profile
> fix: fix a bad display message

- app/Services/Contact/Avatar/GenerateDefaultAvatar.php
- resources/views/people/_header.blade.php
Force the browser to reload the newly generated avatar by adding some query
> fix: fix avatar browser reload

- CHANGELOG.md
- app/Helpers/helpers.php
- app/Http/Controllers/DAV/Backend/CardDAV/CardDAVBackend.php
- app/Http/Controllers/SettingsController.php
- app/Services/Account/Photo/UploadPhoto.php
- app/Services/VCard/ImportVCard.php
- tests/Api/DAV/VCardContactTest.php
Fix #2092
Limitation: if a contact already has a photo as avatar, the new PHOTO scheme will be ignored. This prevent uploading the same photo multiple times.
> feat: vcard photo import

- CHANGELOG.md
- app/Models/Account/Activity.php
- app/Models/Contact/Call.php
- app/Models/Contact/Contact.php
- app/Models/Contact/Debt.php
- app/Models/Contact/Note.php
- app/Models/Contact/Task.php
- app/Models/Journal/JournalEntry.php
- routes/web.php
Reduce number of queries on dashboard and journal.
> perf: reduce queries number

- CHANGELOG.md
- app/Console/Commands/OneTime/MoveAvatars.php
- app/Console/Commands/OneTime/MoveAvatarsToPhotosDirectory.php
- app/Console/Commands/PingVersionServer.php
- scripts/docker/entrypoint.sh
> feat: create passport keys for OAuth access on docker image

- CHANGELOG.md
- resources/views/people/relationship/edit.blade.php
- resources/views/people/relationship/new.blade.php
Fix ability to edit a relationship and switch for a partial contact to a real contact.
> fix: fix partial/real contact edit on relationship

- package.json
- yarn.lock
> chore(deps): update v-selectmenu to version 2.0.1

- CHANGELOG.md
- app/Helpers/RequestHelper.php
> fix: fix getting infos about country without providing ip

- database/migrations/2019_05_26_000000_add_relationship_table_indexes.php
- database/migrations/2019_05_27_000000_populate_relationship_type_tables_with_stepparent_values.php
Optimize migration script for adding stepparrent relationship types (from 12min to 4min !)
> perf: optimize stepparent migration

- CHANGELOG.md
- database/migrations/2019_09_04_075311_fix_tattoo_or_piercing_translation.php
> fix: fix tattoo or piercing translation

- app/Models/Contact/Contact.php
- database/factories/ModelFactory.php
fix default gravatar url construction
> fix: fix default gravatar url

- CHANGELOG.md
- app/Helpers/SearchHelper.php
- app/Http/Controllers/ContactsController.php
- app/Traits/Searchable.php
> fix: fix query and scope searches with table prefix

- CHANGELOG.md
- resources/views/people/_header.blade.php
> fix: fix people header file

- CHANGELOG.md
- composer.json
- composer.lock
- docs/contribute/index.md
- docs/installation/debian.md
- docs/installation/generic.md
- docs/installation/index.md
> chore: revert depends on php7.2+

- package.json
- yarn.lock
> chore(dev-deps): update cross-env to version 6.0.3

- .env.dev
- scripts/docker/000-default.conf
- scripts/docker/entrypoint.sh
> fix: fix docker images

- app/Helpers/DBHelper.php
- app/Helpers/SearchHelper.php
- app/Http/Controllers/ContactsController.php
- app/Traits/Searchable.php
- database/migrations/2017_06_07_173437_add_multiple_genders_choices.php
- database/migrations/2018_10_07_120133_fix_json_column.php
See https://github.com/monicahq/monica/pull/3107#discussion_r339092137
> chore: add helper to get prefix table

- CHANGELOG.md
- app/Http/Controllers/Auth/RegisterController.php
> fix: ensure disable_signup is checked on form register validation

- CHANGELOG.md
- app/Services/Account/Photo/UploadPhoto.php
- app/Services/VCard/ImportVCard.php
- composer.json
- composer.lock
- database/seeds/FakeContentTableSeeder.php
This fixes the case when CSV could contain photos that are weirdly encoded and thus break the import process. We know simply ignore those files.
It also fixes #3175 which is triggered by the latest version of DBAL which breaks the `change()` method in a migration file.
> fix: fix CSV uploads with weird photo files

- docs/installation/generic.md
> docs: add missing required php extension

- .platform.app.yaml
- .platform/routes.yaml
- .platform/services.yaml
> chore: add platform.sh files

- CHANGELOG.md
- app/Models/Contact/Contact.php
- app/Services/Contact/Relationship/DestroyRelationship.php
> fix: fix relationship create and destroy with partial contact

- CHANGELOG.md
- config/app.php
- resources/views/settings/subscriptions/account.blade.php
> fix: fix subscription page

- CHANGELOG.md
- app/Models/Account/Photo.php
- resources/views/settings/storage/index.blade.php
> fix: fix photo-contact relation

- CHANGELOG.md
- resources/views/journal/edit.blade.php
> fix: fix journal entry edit

- resources/views/settings/storage/index.blade.php
> fix: fix photos page if contact is null

- app/Http/Controllers/Api/Account/Activity/ApiActivityTypeCategoryController.php
- app/Http/Controllers/Api/Account/Activity/ApiActivityTypeController.php
- app/Http/Controllers/Api/Account/ApiCompanyController.php
- app/Http/Controllers/Api/Account/ApiGenderController.php
- app/Http/Controllers/Api/Account/ApiPlaceController.php
- app/Http/Controllers/Api/ApiContactController.php
- app/Http/Controllers/Api/ApiContactFieldController.php
- app/Http/Controllers/Api/ApiDebtController.php
- app/Http/Controllers/Api/ApiGiftController.php
- app/Http/Controllers/Api/ApiJournalController.php
- app/Http/Controllers/Api/ApiNoteController.php
- app/Http/Controllers/Api/ApiPetController.php
- app/Http/Controllers/Api/ApiReminderController.php
- app/Http/Controllers/Api/ApiTagController.php
- app/Http/Controllers/Api/ApiTaskController.php
- app/Http/Controllers/Api/Contact/ApiAddressController.php
- app/Http/Controllers/Api/Contact/ApiCallController.php
- app/Http/Controllers/Api/Contact/ApiConversationController.php
- app/Http/Controllers/Api/Contact/ApiLifeEventController.php
- app/Http/Controllers/Api/Contact/ApiMessageController.php
- app/Http/Controllers/Api/Contact/ApiOccupationController.php
- app/Http/Controllers/Api/Settings/ApiContactFieldTypeController.php
- tests/Api/Account/ApiGenderControllerTest.php
> fix: fix request all usage

- app/Http/Controllers/Account/Activity/ActivityTypeCategoriesController.php
- app/Http/Controllers/Account/Activity/ActivityTypesController.php
- app/Http/Controllers/ActivitiesController.php
- app/Http/Controllers/Api/Account/ApiUserController.php
- app/Http/Controllers/Api/ApiActivityController.php
- app/Http/Controllers/Api/ApiContactController.php
- app/Http/Controllers/Api/ApiContactTagController.php
- app/Http/Controllers/Api/ApiController.php
- app/Http/Controllers/Api/ApiNoteController.php
- app/Http/Controllers/Api/ApiRelationshipController.php
- app/Http/Controllers/Api/ApiTaskController.php
- app/Http/Controllers/Auth/EmailChangeController.php
- app/Http/Controllers/Auth/RecoveryLoginController.php
- app/Http/Controllers/Contacts/AvatarController.php
- app/Http/Controllers/Contacts/CallsController.php
- app/Http/Controllers/Contacts/ConversationsController.php
- app/Http/Controllers/Contacts/GiftsController.php
- app/Http/Controllers/Contacts/IntroductionsController.php
- app/Http/Controllers/Contacts/LifeEventsController.php
- app/Http/Controllers/Contacts/NotesController.php
- app/Http/Controllers/Contacts/RelationshipsController.php
- app/Http/Controllers/Contacts/RemindersController.php
- app/Http/Controllers/ContactsController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/JournalController.php
- app/Http/Controllers/Settings/GendersController.php
- app/Http/Controllers/Settings/PersonalizationController.php
- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/TasksController.php
Refactor: use `$request->input` (Laravel) instead of `$request->get` (Symfony)
> refactor: use request input

- docs/installation/mail.md
Added more detailed information about SMTP configuration, generic one while only SES was available.
> fix: Update mail.md to add generic SMTP settings

- scripts/docker/.examples/nginx-proxy/docker-compose.yml
- scripts/docker/apache/Dockerfile
- scripts/docker/entrypoint.sh
- scripts/docker/fpm/Dockerfile
- scripts/docker/php-apache/Dockerfile
- scripts/docker/upgrade.exclude
Monica sources are now in /usr/src/monica, and we use rsync to sync to /var/www/monica.
That way we can have a volume bin to /var/www/monica updated.
> fix: fix docker instances

- CHANGELOG.md
- resources/views/people/conversations/edit.blade.php
> fix: fix edit conversation date not being editable

- database/migrations/2019_12_21_100315_change_gift_status.php
> fix: fix gift photo migration again

- tests/Unit/Models/SpecialDateTest.php
> chore: fix this test that won t work on 29th feb

- composer.json
- composer.lock
The package is required if AndroidSafetyNet is activated
> chore(deps): add web-token/jwt-key-mgmt package

- CHANGELOG.md
- scripts/docker/.examples/nginx-proxy-self-signed-ssl/web/nginx.conf
- scripts/docker/.examples/nginx-proxy/web/nginx.conf
- scripts/docker/.examples/supervisor/fpm/web/nginx.conf
Improve nginx conf on docker examples.
This fix carddav/caldav redirect, and improve HSTS support.
> feat: improve nginx config docker examples

- CHANGELOG.md
- app/Exceptions/Handler.php
- app/Http/Controllers/Auth/InvitationController.php
- app/Http/Controllers/SettingsController.php
- app/Http/Middleware/Authenticate.php
- app/Providers/RouteServiceProvider.php
- routes/web.php
- tests/Feature/Authentication/AuthenticateTest.php
> fix: fix login route already set by Laravel now

- CHANGELOG.md
- app/Console/Commands/SetupTest.php
> fix: SetupTest.php ErrorException: Trying to get property 'id' of non-object

- .platform.app.yaml
- .platform/routes.yaml
> chore: update platform.sh file

- app/Console/Commands/SentryRelease.php
> chore: fix sentry release

- app/Http/Controllers/ContactsController.php
- app/Traits/Searchable.php
> chore: fix search broken in #3852

- .env.dev
- .env.example
- config/mail.php
- docs/contribute/index.md
- docs/installation/mail.md
- docs/installation/providers/heroku.md
- phpunit.xml
Fix this big unbelievable bug introduced in #3746
> fix: fix mail config setting

- CHANGELOG.md
- database/migrations/2020_04_24_185810_remove_duplicate_currency.php
> fix: fix currency in double

- CHANGELOG.md
- database/migrations/2020_05_08_072433_google2fa_column_size.php
> fix: fix google2fa column size

- readme.md
A very small thing, but I've just started exploring Monica and like it, so figured I'd make a small contribution. If I can dust off my PHP, I might try to do something more significant :)
> docs: updating the copyright to 2020 in the readme

- app/Models/User/User.php
- app/Services/Account/Photo/UploadPhoto.php
- app/Services/Contact/Gift/UpdateGift.php
- composer.json
- composer.lock
- phpstan.neon
> chore(deps): Upgrade Larastan to 0.6

- docs/installation/providers/heroku.md
> docs: fix "invisible" images in heroku documentation

- scripts/docker/.examples/supervisor/fpm/app/supervisord.conf
> docs: php-fpm7 is located in /usr/sbin

- .env.example
- app/Http/Controllers/Api/Auth/OAuthController.php
- config/monica.php
- config/passport.php
- database/migrations/2020_08_05_184814_upgrade_passport.php
- docs/installation/providers/generic.md
- docs/installation/providers/heroku.md
- tests/Browser/Auth/AuthControllerTest.php
See https://github.com/laravel/passport/blob/master/UPGRADE.md
> feat: update passport conf and env. variables

- .github/workflows/sqlite.yml
Fetch the whole history on reporting so sonarcloud has all information
> chore: fetch the whole history for sonarcloud

- docs/installation/readme.md
to include docker link in context.
> docs: update readme.md

- docs/contribute/readme.md
- docs/contribute/translate.md
- docs/installation/providers/generic.md
- docs/installation/update.md
Fix errors in documentation by issue #4580 and parcipiating in hacktoberfest 2020.
> docs: fix misspellings in documentation

- app/Providers/AppServiceProvider.php
- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
fix passport install so `php artisan migrate --database testing` still works
> fix: fix passport setup migration

- docs/installation/providers/generic.md
> docs: imagick is required

- scripts/docker/Dockerfile
> ci: fix docker master build

- .github/workflows/cypress.yml
> chore: change cypress workflow

- app/Helpers/ComposerScripts.php
Fixes: https://github.com/monicahq/monica/issues/4640
> fix: heroku build and deploy

- readme.md
> minor grammar correction

- app/Models/Contact/Contact.php
- tests/Feature/ContactTest.php
> refactor: refactor contacts sorting for readability

- scripts/ci/fixsecrets.sh
> chore: fix secrets mapping

- docs/installation/providers/debian.md
> docs: Update debian.md to include php-imagick requirement

- CHANGELOG.md
- app/Http/Controllers/Api/Auth/OAuthController.php
- tests/Browser/Auth/AuthControllerTest.php
> fix: fix oauth login bad credentials

- composer.json
This PR
💁‍♂️ I ran
```
$ composer global require ergebnis/composer-normalize
```
followed by
```
$ composer normalize
```
For reference, see https://github.com/ergebnis/composer-normalize.
❗ Disclaimer: I'm the maintainer of `ergebnis/composer-normalize`.
> chore: normalize composer.json

- app/Http/Controllers/Api/ApiController.php
setSQLOrderByQuery function simplified.
> refactor: simplify setSQLOrderByQuery function

- app/Console/Kernel.php
This load all commands at once without having to declare them one by one
> refactor: load commands at once

- .github/workflows/lock.yml
> ci: add lock-threads action workflow

- routes/web.php
> refactor: add .well-known redirects

- LICENSE
- README.md
> style: add heroku button on readme

- scripts/docker/Dockerfile
> ci: fix docker dev build

- app/Services/Contact/Avatar/GetAdorableAvatarURL.php
- config/monica.php
- database/migrations/2021_01_10_235600_update_adorable_api.php
> refactor: allow to setup your own adorable api url

- resources/views/dashboard/index.blade.php
Minor fix so that both "Events" and "Changes" header are bold and evenly spaced.  Added divider between title of "Product changes" and the list for consistency.
> style: Minor fix to style and spacing of headers on Dashboard.

- config/cache.php
- config/passport.php
> refactor: update config cache and passport

- CONTRIBUTORS
> docs: name & handle change of a contributor name

- docs/installation/providers/heroku.md
> docs: Add update link in Heroku installation docs

- README.md
This minimum requirement is based on my own use over the last three months.  Monica works on my Debian VPS with 256MB of RAM, albeit quite slowly at times.
> docs: Added minimum hardware requirements to README (closes #4677).

- config/logging.php
Create a new stacked log channel to combine papertrail and syslog
> feat: create a new stacked log channel

- .releaserc
change `refactor` handle with default configuration
> ci: change releaserc releaseRules

- app/Http/Controllers/SettingsController.php
- app/Models/Account/ImportJob.php
We cannot use the 'public' filesystem anymore
> fix: fix importvcard job

- tests/Api/Contact/ApiContactControllerTest.php
> test: fix a flaky test

- resources/views/vendor/mail/html/message.blade.php
- resources/views/vendor/mail/text/message.blade.php
> style: fix email name signature

- composer.json
- composer.lock
Laravel's tinker package is super useful for new devs to the project to poke around at the code and explore how things work.
> chore: adding laravel/tinker for development

- app/Helpers/CountriesHelper.php
- config/lang-detector.php
- resources/js/pluralization.js
- resources/lang/en/settings.php
- tests/Unit/Helpers/CountryHelperTest.php
- webpack.mix.js
Kudos to [`whenwesober`](https://crowdin.com/profile/whenwesober) on crowdin 👍🏽
> feat: add Indonesian language

- app/Services/VCard/ImportVCard.php
- tests/Unit/Services/VCard/ImportVCardTest.php
Import notes on a vcard entry. This fix #1426
> feat: add notes when importing vcard

- app/Helpers/SearchHelper.php
- app/Models/Contact/Contact.php
Search sent wrong results, related to #5103
> fix: fix search with additional info

- app/Http/Controllers/SettingsController.php
- app/Http/Requests/SettingsRequest.php
- app/Models/User/User.php
- resources/views/settings/index.blade.php
> fix: fix layout selection

- resources/views/settings/export.blade.php
- routes/web.php
- tests/Feature/SettingsTest.php
> fix: use post request for exportToSql

- config/lang-detector.php
- resources/lang/en/settings.php
- webpack.mix.js
Translate 95%. Some emotion string will translate soon
> feat: add Vietnamese language

- config/lang-detector.php
- resources/lang/en/settings.php
- webpack.mix.js
Hi!
I'm new on Github (sorry If I didn't the things the right way).
I recently translated Monica to pt-BR (Crowdin).
Add language pt-BR
First of all, thanks so much for taking the time to open a pull request and help the project. It's because of people like you that we love working on this project.
Please read the list below. Feel free to delete this text after, but we need you to read it so we make sure that the project is consistent and remains of quality.
This close #5331
> feat: add Portuguese-BR language

- .github/workflows/docker.yml
Fix ghcr.io/monicahq/monica image
> refactor: fix docker dev build

- docs/contribute/readme.md
- docs/installation/faq.md
- docs/installation/mail.md
- docs/installation/providers/cpanel.md
- docs/installation/providers/heroku.md
Just cleaning up some typos in the docs
> docs: typofixes

- docs/installation/storage.md
> fix(docs): remove https prefix from AWS_ENDPOINT

- app/Http/Controllers/Contacts/GiftController.php
- resources/js/components/people/gifts/CreateGift.vue
- resources/js/components/people/gifts/Gifts.vue
- routes/web.php
This fix #5633
fix #5516
fix #4862
fix #3442
> fix: fix gift api without passport

- docs/installation/update.md
One should activate foreign key checks after everything is done, not deactivate again
> docs: fix sloppy mistake in update.md

- app/Models/Account/Weather.php
- app/Services/Instance/Geolocalization/GetGPSCoordinate.php
- resources/views/people/profile.blade.php
> fix: fix weather get

- docs/user/carddav.md
> docs: Fix typos in carddav.md

- database/migrations/2017_07_22_153209_create_instance_table.php
This will only change new instance's uuid
> refactor: use uuid to identify instances

- app/Http/Controllers/Api/ApiController.php
- routes/api.php
> fix: add link to reminders endpoint at api root

- app/Helpers/DateHelper.php
- app/Helpers/InstanceHelper.php
- app/Http/Controllers/Contacts/ConversationsController.php
- app/Models/Account/ImportJob.php
- app/Models/Contact/Reminder.php
- app/Models/Instance/SpecialDate.php
- app/Models/Journal/JournalEntry.php
- app/Models/User/Changelog.php
- app/Services/VCalendar/ImportTask.php
- phpunit.xml
- tests/Unit/Helpers/DateHelperTest.php
This fix #887
This worked before, but #3655 broked it.
> fix: fix Date display with timezone

- app/Console/Commands/Tests/UpdateLangs.php
- composer.json
- composer.lock
- resources/lang/ar.json
- resources/lang/de.json
- resources/lang/es.json
- resources/lang/fi.json
- resources/lang/id.json
- resources/lang/it.json
- resources/lang/ja.json
- resources/lang/nl.json
- resources/lang/ru.json
- resources/lang/tr.json
- resources/lang/vi.json
This introduce a new command `setup:updatelang` only available in test mode.
It require installing an extra package, which isn't included by default.
> chore: update langs json file automatically

- app/Http/Controllers/Contacts/NotesController.php
- resources/js/components/people/StayInTouch.vue
- resources/js/components/people/photo/PhotoList.vue
- resources/views/people/_header.blade.php
- resources/views/people/photos/index.blade.php
- resources/views/people/profile.blade.php
This fix passing the entire contact data to the stay-in-touch vue.
It also fix some glitches for vue
> refactor: optimize stayInTouch data passed

- app/Models/Contact/Contact.php
- app/Services/Contact/Avatar/GetAdorableAvatarURL.php
- composer.json
- composer.lock
- config/monica.php
- tests/Unit/Models/ContactTest.php
- tests/Unit/Services/Contact/Avatar/GetAdorableAvatarTest.php
This time we'll use [asbiin/laravel-adorable](https://github.com/asbiin/laravel-adorable) which give a data-url and is a permanent solution.
> feat: re-activate adorable avatars with permanent solution

- app/ExportResources/Contact/Contact.php
- app/Models/Contact/Contact.php
- resources/js/components/people/ContactList.vue
- resources/js/components/people/partials/ContactAutosuggest.vue
- resources/views/people/avatar/edit.blade.php
- tests/Unit/Models/ContactTest.php
This fix #5880
Also remove data-url content from json export
> fix: fix contact search + adorable return data

- scripts/docker/Dockerfile
> ci: fix docker developpement build

- docs/installation/storage.md
Update documentation after discussion on #5846
> docs: update doc about external storage creation

- .github/workflows/heroku.yml
> ci: deploy to heroku

- .github/workflows/heroku.yml
> ci: fix heroku deploy

- .tool-versions
NA
NA
NA
Small change, no changelog entry.
> chore: bump tool-versions to latest required versions

- .env.example
Correcting a small typo in a comment of `.env.example`
> 'Only' 5000 requests per day, free

- .github/workflows/release.yml
- .github/workflows/semantic.yml
- .releaserc
- CONTRIBUTING.md
- CONTRIBUTORS
See https://www.conventionalcommits.org/en/v1.0.0/
> ci: switch to conventionalcommits

- scripts/vagrant/build/install-monica.sh
not sure someone is using it though
> chore: fix vagrant build

- CONTRIBUTORS
- public/robots.txt
Added disallow on robots.txt for prevent crawlers to index the CRM
> feat: add disallow in robots.txt

- .github/workflows/build.yml
- .github/workflows/cypress.yml
- .github/workflows/deploy.yml
- .github/workflows/docker.yml
- .github/workflows/migration_tests.yml
- .github/workflows/release.yml
- .github/workflows/static.yml
- .github/workflows/tests.yml
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> build: use concurrency

- config/sentry.php
This should fix #6351 
N/A
N/A
> fix(php8.1): deprecated trim with null value

- README.md
This should fix #6337 . Based on https://github.com/platformsh-templates/laravel, we need to indicate the yaml URL in the template attribute.
N/A
N/A
N/A
N/A
> docs: update deploy link to platform.sh

- package.json
- yarn.lock
> chore: use snyk-protect

- docs/installation/providers/ubuntu.md
> docs: Update ubuntu.md

- app/Exceptions/FileNotFoundException.php
- app/Traits/Hasher.php
- composer.json
- composer.lock
- psalm.xml
- tests/DuskTestCase.php
- tests/Unit/Services/DavClient/UpdateSubscriptionLocalSyncTokenTest.php
Update Psalm and laravel-psalm versions, plus update code based on Psalm's output
> chore: update psalm

- docs/installation/providers/docker.md
> docs(docker): preserve user/pass, update link

- app/Domains/Contact/ManageTasks/Web/ViewHelpers/ModuleContactTasksViewHelper.php
- app/Domains/Vault/ManageTasks/Web/ViewHelpers/VaultTasksIndexViewHelper.php
- app/Models/ContactTask.php
- resources/js/Components/Jetstream/ConfirmsPassword.vue
- resources/js/Components/Jetstream/Select.vue
- resources/js/Pages/Profile/Partials/DeleteUserForm.vue
- resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue
- resources/js/Pages/Vault/Contact/ImportantDates/Index.vue
- resources/js/Pages/Vault/Contact/ImportantDates/Partials/CreateOrEditImportantDate.vue
- resources/js/Pages/Vault/Dashboard/Partials/DueTasks.vue
- resources/js/Pages/Vault/Dashboard/Task/Index.vue
- resources/js/Pages/Webauthn/Partials/UpdateKey.vue
- resources/js/Shared/Form/ContactSelector.vue
- resources/js/Shared/Modules/Loans.vue
- resources/js/Shared/Modules/Reminders.vue
- resources/js/Shared/Modules/TaskItems/CreateOrEditTask.vue
- resources/js/Shared/Modules/Tasks.vue
- tests/Unit/Domains/Contact/ManageTasks/Web/ViewHelpers/ModuleContactTasksViewHelperTest.php
- tests/Unit/Domains/Vault/ManageTasks/Web/ViewHelpers/VaultTasksIndexViewHelperTest.php
`setTimeout` isn't a solution. we should use `nextTick`, but the refs components needs to exist, and so we have to use `v-show` directives instead of `v-if`
> fix: fix vue refs targets

- app/Domains/Settings/CreateAccount/Jobs/SetupAccount.php
- app/Domains/Settings/ManageCallReasons/Services/CreateCallReason.php
- database/migrations/2023_06_16_103430_fix_call_reasons.php
- resources/js/Pages/Settings/Personalize/CallReasons/Index.vue
Call reason list was apparently empty
> fix: fix call reasons

- app/Domains/Settings/ManageUserPreferences/Services/StoreLocale.php
- app/Domains/Settings/ManageUserPreferences/Web/ViewHelpers/UserPreferencesIndexViewHelper.php
- database/migrations/2023_06_28_102228_fix_locale.php
- resources/js/Pages/Settings/Preferences/Partials/Locale.vue
- resources/js/Shared/Modules/ContactInformation.vue
- tests/Unit/Domains/Settings/ManageUserPreferences/Web/ViewHelpers/UserPreferencesIndexViewHelperTest.php
The new locale was stored as an integer, instead of storing the locale value.
> fix: fix setting a locale

- resources/js/Pages/Webauthn/WebauthnLogin.vue
This is only visible when building on prod
> fix: fix useForm

- app/Domains/Settings/ManageTemplates/Services/CreateTemplatePage.php
- app/Domains/Settings/ManageTemplates/Services/UpdateTemplatePage.php
- app/Domains/Vault/ManageReports/Web/Controllers/ReportAddressesCitiesController.php
- app/Domains/Vault/ManageReports/Web/Controllers/ReportAddressesCountriesController.php
- app/Domains/Vault/ManageReports/Web/ViewHelpers/ReportAddressIndexViewHelper.php
- app/Domains/Vault/ManageReports/Web/ViewHelpers/ReportCitiesShowViewHelper.php
- app/Domains/Vault/ManageReports/Web/ViewHelpers/ReportCountriesShowViewHelper.php
- app/Domains/Vault/ManageVaultSettings/Services/CreateLabel.php
- app/Domains/Vault/ManageVaultSettings/Services/CreateTag.php
- app/Domains/Vault/ManageVaultSettings/Services/UpdateLabel.php
- app/Domains/Vault/ManageVaultSettings/Services/UpdateTag.php
- app/Helpers/WikipediaHelper.php
- resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue
Fix addresses report that displayed unfiltered values.
Also fixing the wikipedia search to look in the current language.
> fix: fix addresses report list

- app/Domains/Contact/Dav/ExportVCardResource.php
- app/Domains/Contact/Dav/ImportVCardResource.php
- app/Domains/Contact/Dav/Importer.php
- app/Domains/Contact/Dav/Jobs/UpdateVCard.php
- app/Domains/Contact/Dav/Services/ExportVCard.php
- app/Domains/Contact/Dav/Services/GetEtag.php
- app/Domains/Contact/Dav/Services/ImportVCard.php
- app/Domains/Contact/Dav/VCardResource.php
- app/Domains/Contact/Dav/Web/Backend/CardDAV/CardDAVBackend.php
- app/Domains/Contact/Dav/Web/Backend/SyncDAVBackend.php
- app/Domains/Contact/ManageContact/Dav/ExportNames.php
- app/Domains/Contact/ManageContact/Dav/ExportTimestamp.php
- app/Domains/Contact/ManageContact/Dav/ImportContact.php
- app/Domains/Settings/ManageGenders/Dav/ExportGender.php
- app/Helpers/helpers.php
- app/Models/Contact.php
- app/Models/Group.php
- app/Models/Vault.php
- app/Providers/DAVServiceProvider.php
- app/Services/BaseService.php
- database/migrations/2020_04_25_133132_create_contacts_table.php
- database/migrations/2021_10_09_204235_create_group_table.php
- database/migrations/2023_07_29_200200_add_contact_distant_uri.php
- database/migrations/2023_07_29_200200_add_groups_distant_uri.php
- tests/Unit/Domains/Contact/DAV/Jobs/UpdateVCardTest.php
- tests/Unit/Domains/Contact/DAV/Services/GetEtagTest.php
- tests/Unit/Domains/Contact/DAV/Services/ImportVCardTest.php
- tests/Unit/Domains/Contact/ManageContact/Dav/ImportContactTest.php
- tests/Unit/Domains/Contact/ManageGroups/Services/DestroyGroupTest.php
Use generics
Add columns to contact and groups
> refactor: import and export vcard improvements

- docs/installation/providers/ubuntu.md
Tested this on a new installed of Ubuntu Server 22.04
> docs: Update Ubuntu Install guide

- app/Domains/Settings/CreateAccount/Jobs/SetupAccount.php
- app/Domains/Settings/ManageTemplates/Services/CreateTemplate.php
- app/Domains/Settings/ManageTemplates/Web/ViewHelpers/PersonalizeTemplateIndexViewHelper.php
- app/Models/Template.php
- database/migrations/2023_10_02_195229_add_can_be_deleted_to_templates.php
- resources/js/Pages/Settings/Personalize/Templates/Index.vue
- resources/js/Pages/Settings/Personalize/Templates/Partials/Pages.vue
- tests/Unit/Domains/Settings/CreateAccount/Services/SetupAccountTest.php
- tests/Unit/Domains/Settings/ManageTemplates/Web/ViewHelpers/PersonalizeTemplateIndexViewHelperTest.php
Fix https://github.com/monicahq/monica/issues/6839
> fix: default template cant be deleted

- resources/views/app.blade.php
Hi team,
I have fixed a syntax error in app.blade.php that was causing the application to error out. The error was caused by a missing semicolon at the end of a line. I have added the missing semicolon and tested the fix to ensure that the application now loads correctly.
Please review my changes and let me know if you have any questions or concerns.
Thanks,
Ahmod Hasan
> fix: fix syntax error

- app/Domains/Contact/ManageContact/Web/Controllers/ContactController.php
> fix: correct ordering of contacts based on preferred displaying of names

- resources/views/journal/add.blade.php
This is a possible accessibility problem.
> fix: fix incorrect connection between date label and input

- .github/workflows/build_assets.yml
- .github/workflows/docker.yml
- .github/workflows/lint_vue.yml
- .github/workflows/release.yml
- .github/workflows/static_analysis.yml
- .github/workflows/tests.yml
Fix docker tag set
Fix yarn cache
Fix conditions
> ci: update workflows

- app/Helpers/StorageHelper.php
- tests/Unit/Helpers/StorageHelperTest.php
> fix: storage_limit can be unlimited

- config/mail.php
Allows custom sendmail-commands for eg. pgp-encrypted emails ( https://github.com/monicahq/monica/issues/6338 )
> feat: added sendmail-env for custom-sendmail-command

- app/Http/Controllers/SettingsController.php
This PR is created to fix this issue #5981 I choose to fix the issue without any schema miniputation
this is a Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative
> fix(settings): appending the me-contact only if it is not null

- config/mail.php
allow disabling cert verification with docker. This is a behavior change after 3.7
> feat: allow disabling cert verification

- scripts/docker/Dockerfile
> ci: fix docker build with memcached

- .github/workflows/tests.yml
- app/Http/Controllers/ContactsController.php
- composer.json
- composer.lock
> fix: fix contact tags count

- app/Http/Controllers/ContactsController.php
- app/Models/Contact/Contact.php
- resources/views/people/index.blade.php
PART OF GTC OPEN SOURCE INTIATIVE
issue #6708 
> fix: selected sort not updated first time selected

- resources/js/Shared/Modules/Notes.vue
> feat: show notes as multi-line instead of single line

- composer.json
- composer.lock
- phpstan.neon
This PR updates `larastan` to `larastan/larastan` It moved to a new organization recently.
> chore(deps): update to larastan/larastan

- app/Providers/EventServiceProvider.php
- composer.json
- composer.lock
- config/auth.php
- config/services.php
- lang/de/auth.php
- lang/en/auth.php
- lang/es/auth.php
- lang/fr/auth.php
- lang/it/auth.php
- lang/ml/auth.php
- lang/pt/auth.php
- lang/ru/auth.php
- resources/js/Pages/Vault/Index.vue
Since Elon Musk's take over of Twitter, this social network became a place of arrogance, racism, and conspiracy, making it the heaven for extreme right thoughts.
I can no longer support this social network, and so I'm removing the login provider support for it.
> feat: remove twitter socialite provider

- app/Http/Controllers/Auth/AcceptInvitationController.php
- resources/js/Pages/Auth/Login.vue
- resources/js/Pages/Auth/Register.vue
- resources/js/Shared/Guest.vue
- We now require a password of at least 8 characters long, but nothing more. we don't need rules like special characters, uppercase/lowercase and all that crap.
- Slight visual adjustements on the login and register page.
> chore: change registration mechanisms

- lang/fr.json
> fix: fix typo in fr.json

- app/Helpers/helpers.php
- app/Providers/AppServiceProvider.php
- app/Providers/TelescopeServiceProvider.php
- bootstrap/providers.php
- composer.json
- composer.lock
- config/pulse.php
- database/migrations/2023_06_07_000001_create_pulse_tables.php
- phpunit.xml
- resources/views/vendor/pulse/dashboard.blade.php
Transition from Telescope to Pulse for monitoring and debugging, including necessary configuration changes and new database migrations for Pulse data structures. This update enhances the application's observability features.
> feat(debug): replace telescope with pulse

- app/Domains/Vault/Search/Web/ViewHelpers/VaultSearchIndexViewHelper.php
- resources/js/Pages/Profile/Partials/UpdateProviders.vue
- resources/js/Pages/Vault/Search/Index.vue
- resources/js/Pages/Vault/Search/Partials/Note.vue
Correct the search group link and enhance the search component by implementing a reactive search feature that fetches results based on user input.
> fix: fix search group link and improve search functionality
