readme.md
"It's like an assistant (some call it spouse) you dream you had." might rub some people the wrong way, and the purpose is clearer and more to-the-point without it anyway.
(feel free to simply close this if you disagree, just my 2 cents ;) )
=> Shorten 'purpose' section

resources/views/settings/index.blade.php
Fixes #132 
Includes:
- Berlin/Bern Problem (#132)
- Removal of doubled entry for paris
- Weird space für UTC
I'm not sure whether this PR includes everything that's needed, but I didn't find any other mentions of these timezones in the code.
=> Fix wrong Timezone settings (#132)

database/migrations/2017_05_04_193252_alter_activity_nullable.php
Postgres doesn't work with backticks; makes sense to use actual Laravel migration syntax for changing columns where possible to allow SQL grammar to take care of the rest.
=> Fix migrations for Postgres

app/Entry.php, database/migrations/2017_06_11_025227_remove_encryption_journal.php, tests/Unit/EntryTest.php
I used to encrypt this but the decryption randomly generates problems sometimes. I wonder why. Is it because of special characters that are included and get corrupted while encrypted? I don't know, but I've found that removing the encryption (which is not necessary anyway), solves the problem - until we find a better solution.
=> Remove encryption in the journal table

resources/views/dashboard/index.blade.php, resources/views/layouts/skeleton.blade.php
Provides a temporary fix for #26. The problem has been fixed in the [Bootstrap v4-dev branch](https://github.com/twbs/bootstrap/pull/21807) but has not yet been released - hopefully won't be too long. 
Summary:
- Added a 'scripts' [stack](https://laravel.com/docs/5.4/blade#stacks) to the layout file, so that the javascript fix doesn't have to be present on all pages
- Added a temporary javascript fix to manually add/remove the "active" class from the tabs when clicked
=> Temporarily fix Bootstrap tabs (#26)

resources/views/people/dashboard/people-information/index.blade.php
I do not know php so there may be a way to only call `getEmail` once (so we don't have to fetch it over and over again). If so please let me know and I'll do that.
If there is a better way to implement this I am certainly all for that too.
If merged this will close #208.
=> Change the email text to be a mailto link

resources/views/dashboard/index.blade.php
=> Fix debt description on the dashboard not fetching the localized 'debts_for' resource

app/Console/Commands/ImportVCards.php, app/Console/Kernel.php, composer.json, composer.lock, tests/Unit/ImportVCardsTest.php, tests/stubs/vcard_stub.vcf
This pull request adds a command to import vcards (similar to #60 ).
Usage: `php artisan import:vcard {user: User's email address} {path: Path to a .vcf file}`
The command checks whether an email already exists, so duplicates shouldn't be an issue. However, I think the unique constraint is too eager. If another user wants to add the same person (whether through import or otherwise), they will not be added. I think this is a bug and the constraint should be `['account_id', 'email']`. I can handle it in another pull request.
=> Add import:vcard command

app/Contact.php, app/Task.php, resources/views/people/debt/index.blade.php
Debts are not displayed anymore. This is because of two things:
* First, the model association was wrongly named (a `s` was missing)
* Second, the `hasDebt` method were always right due to the nature of the relationship.
=> Fix debts display

Dockerfile
@djaiss This adds the php7-xmlreader module that the new sabre dependencies require.
=> Added php7-xmlreader to Docker as a new requirement

docs/installation/heroku.md
Hi there.  Thanks for creating Monica and adding a Heroku Deploy button.  I'm hoping to highlight this Deploy Button in Heroku's monthly newsletter for June.
Here are a few changes to the Heroku deploy instructions that I think will make it easier for others to deploy to Heroku and use.
- Fix deploy button URL (without specifying the `template=` query string variable, it looks at the referring URL which doesn't work since this button no longer lives in the root README file)
- Specify that email configuration isn't required (this confused me for a few minutes.  I didn't realize I could register the first user without having email properly setup.)
- Suggest free Mailgun add-on to setup email (Easy way to get email working for free.)
=> Fix/improve Heroku Deploy button and instructions

resources/views/settings/index.blade.php
In the commit 9cb7de7f1b5e86718e8f2b2f7a9ff7400ca6b496 the time zone
Europe/Bern got removed.
However this left Switzerland without a time zone. The proper time zone
name for Switzerland is Europe/Zurich.
#132
=> add time zone for Switzerland

readme.md
On some systems it's not possible to import a .vcf file if it isn't in the root
of the installation. To reduce issues about imports that don't work I updated
the readme with a way that should work on every system.
#263
=> update the section about the vcf import

CHANGELOG, app/Contact.php, app/Http/Controllers/People/KidsController.php, app/Http/Controllers/People/SignificantOthersController.php, app/Http/Controllers/PeopleController.php, app/Reminder.php, database/migrations/2017_06_16_215256_add_about_who_to_reminders.php, resources/lang/en/people.php, resources/views/people/reminders/form.blade.php, resources/views/people/reminders/index.blade.php
* When adding an exact birthdate for a contact, a significant other or a kid, a reminder is now automatically created.
* When editing this date, the reminder will be automatically updated.
* When deleting the object, the associated reminder will be deleted.
* Fix birthdate data in production.
* Add a new way of tracking birthdays in the reminders table.
This will also fix #325
=> Add birthday automatically when defining a birthdate

resources/lang/en/dashboard.php, resources/views/dashboard/index.blade.php
Note: The initial commit only updates the `en` translation source.
I do not know other languages well enough to update them properly.
=> Dashboard: Use singular 'day' when a reminder is scheduled for 1 day

resources/views/people/gifts/index.blade.php
This commit updates the gift UI to hide the `value`, `link` and
`comment` blocks when the values are not set. The usage of `is_null`
does not work because when the values are empty strings when not set.
=> Hide gift value, link and comment when not set

Dockerfile
To prevent this error from happening during ```docker-compose build```
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for stripe/stripe-php v4.13.0 -> satisfiable by stripe/stripe-php[v4.13.0].
- stripe/stripe-php v4.13.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
Problem 2
- stripe/stripe-php v4.13.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
- laravel/cashier v7.0.9 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.13.0].
- Installation request for laravel/cashier v7.0.9 -> satisfiable by …
```
=> Add php7-curl dependency to Dockerfile

app/Http/Middleware/CheckLocale.php, resources/views/dashboard/index.blade.php
Changed the way the 'Last Actions' tab shows event timestamps, at first glance it's hard to reason how long ago an action took place without counting backwards from the current date, updated to use Carbons diffForHumans.
**Before**
**After**
=> show time diff from when action was created to now

CHANGELOG, app/Http/Controllers/PeopleController.php, app/Http/Requests/People/KidsRequest.php, app/Http/Requests/People/RelationshipsRequest.php
Facebook's longest names are limited to 50 characters. We'll do the same, which will make sure the UI doesn't break when names are too long.
=> Restrict people name's length

tests/Feature/InstanceTest.php, tests/Feature/VersionCheckTest.php, tests/Unit/AccountTest.php
We've used putenv() to set environment variables in tests forcing us
to reload the environment. We don't have to if we use the config
helper in Laravel instead.
=> Use the config helper instead of putenv

resources/lang/en/dashboard.php
Currently if no notes are starred, an incomplete message is shown on the relevant page. This PR fixes that.
=> Fix typo related to starred notes

composer.json, composer.lock
```
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for symfony/event-dispatcher v4.0.1 -> satisfiable by symfony/event-dispatcher[v4.0.1].
- symfony/event-dispatcher v4.0.1 requires php ^7.1.3 -> your PHP version (7.1.0) does not satisfy that requirement.
Problem 2
- symfony/event-dispatcher v4.0.1 requires php ^7.1.3 -> your PHP version (7.1.0) does not satisfy that requirement.
- symfony/http-kernel v3.4.1 requires symfony/event-dispatcher ~2.8|~3.0|~4.0 -> satisfiable by symfony/event-dispatcher[v4.0.1].
- Installation request for symfony/http-kernel v3.4.1 -> satisfiable by symfony/http-kernel[v3.4.1].
```
=> Fix composer update

app/Http/Controllers/SettingsController.php, resources/views/partials/components/people-upgrade-sidebar.blade.php
```php
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'account_id' in 'where clause' (SQL: delete from `pet_categories` where `account_id` = 10177)
```
=> Fix account deletion

app/Console/Commands/SendNotifications.php, docs/contribute/contribute.md
Fix https://github.com/monicahq/monica/issues/771 
The database has currently reminders with no contacts associated. I don't know why, this sucks, but in the meantime, we need to filter out reminders which do not have contacts.
=> Add check to prevent sending reminder to a contact that does not exist

CHANGELOG, app/Contact.php, app/Http/Resources/Contact/Contact.php, tests/Unit/ContactTest.php
This will close https://github.com/monicahq/chandler/issues/48
=> Fix avatar being invalid in the Contact API call

package.json
Version 2.0.0 does not compile anymore.
=> Revert Laravel mix to 1.7.2

app/Account.php, app/Console/Commands/SetupProduction.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/SettingsController.php, app/User.php, database/factories/ModelFactory.php, database/seeds/FakeContentTableSeeder.php, database/seeds/FakeUserTableSeeder.php, tests/Helper/VCardHelperTest.php, tests/Unit/ImportVCardsTest.php
From a fresh installation, genders table are not set for the first register account/user.
=> Fix genders setup production

docs/installation/docker.md
=> Tiny typo fix

Makefile, docs/contribute/contribute.md, docs/installation/debian.md, docs/installation/docker.md, docs/installation/generic.md, docs/installation/update.md
=> Update installation docs

config/sentry.php
This fixes #872.
If you run `php artisan config:cache` the command will be run once.
=> Sentry config file: test if .git directory is present

scripts/docker/test-server.sh, scripts/tests/fix-bintray.sh, scripts/tests/realpath.sh, scripts/tests/runtests.sh, scripts/tests/start-selenium.sh
=> Fix docker image creating wrong storage directories

composer.json, composer.lock, config/app.php
Remove debugbar from production, suggested to only install it on dev environments. Especially for personal information like this. (Eg. people who accidentally forget to disable DEBUG).
Also bumped to 3.x. ServiceProvider is no longer required because of the auto detecting of packages.
=> Require debugbar on dev only

app/Console/Commands/PingVersionServer.php, database/seeds/DatabaseSeeder.php
env() calls should not be run outside config/ or tests/ directories.
Laravel doc specify explitely to use `App::environment()`
https://laravel.com/docs/5.5/configuration#determining-the-current-environment
=> Remove env calls

.codecov.yml
See https://docs.codecov.io/docs/codecov-yaml
This should (I hope) fix bad codecov reporting coverage decrease when diff is 0%
=> Add codecov yaml file

CHANGELOG, app/Http/Controllers/Api/ApiContactController.php, app/Http/Controllers/Api/ApiController.php, app/Http/Controllers/Api/ApiTaskController.php, config/api.php
This PR adds the ability to sort tasks by the `completed_at` attribute. This will close https://github.com/monicahq/chandler/issues/127
=> Add ability to sort tasks by completed_at

app/Http/Controllers/ContactsController.php
Hello hello,
I bumped into an issue on master when editing a contact, the order of parameters in ContactsController:243 (firstName, middleName, lastName) is different than in the function being called at Contact:729 (firstName, lastName, middleName = null), which results in an exception.
I have not added a test since the whole PR is literally swapping two parameters; I can add it if required, of course.
=> Order lastname and middlename parameters correctly for contact->setName call

.travis.yml, app/Day.php, tests/CreatesApplication.php
=> Use phpdbg and other test improvements

app/Contact.php, tests/Unit/ContactTest.php
Introduced with #971 : this line was missed in the new Contact::deleteEverything function:
https://github.com/monicahq/monica/pull/971/files#diff-da2c468a7e44d4976ad8308dbe22e7faL340
=> Fix contact deletion

app/Console/Commands/Update.php
@asbiin I have to remove the config:cache command from your script.
I don't know why, but this option breaks the production environment on Linode. I have to find out why, but in the meantime, if  I want to deploy, I need to remove it.
=> Remove config:cache in the Update command

CHANGELOG, app/Console/Commands/CalculateStatistics.php, tests/Unit/Commands/CalculateStatisticsTest.php
The command was broken thanks to our latest 2.0.0 version.
=> Fix daily statistics calculation command

resources/views/partials/components/date-select.blade.php, resources/views/people/dashboard/introductions/edit.blade.php
Fixes #1058
The original  `select-date` component only accept default date as a `SpecialDate` model object, I update it to accept `Carbon` as well, and give a default value to `how I meet X ` date picker
=> Make select-date component works with SpecialDate object as an Carbon instance

app/Console/Commands/SendNotifications.php, app/Http/Controllers/Settings/ReminderRulesController.php, app/Jobs/Notification/SendNotificationEmail.php, app/Notification.php, app/ReminderRule.php, database/migrations/2018_05_06_194710_delete_reminder_sent_table.php, tests/Unit/Jobs/SendNotificationEmailTest.php, tests/Unit/NotificationTest.php, tests/Unit/ReminderRuleTest.php
This fixes a bug.
The bug is:
* reminder rules are set to ON (either the 7 or 30 days),
* you create a reminder, the system creates notifications (ie the emails that should be send 7 and 30 days in advance the event will happen),
* before the notifications are sent, set reminder rules to OFF (either the 7 or 30 days),
* currently, the notifications will still be sent (despite being to OFF), as they have been scheduled in the past
So, basically, I've changed it so that if reminder rules are disabled, notifications are not sent.
=> Notifications should not be sent if reminder rule is set to off

CHANGELOG, app/Http/Controllers/ContactsController.php
This fixes #1338 by checking if we already have used that tag, unfortunately the duplicate tags need to stay in the URL unless we want to add more logic to the index method but I believe having a less than pretty URL is better then having a more complicated method. 
@djaiss When ever got get a chance to review.
=> Fixes #1338 Contact tags duplicate when filtering contacts. [Needs Review]

resources/lang/en/app.php, resources/views/compliance/index.blade.php
These url should not be in the text to translate.
Also added a hreflang to inform the user of the language of the destination text.
=> Remove url form text to translate

psalm.xml
Should help #1465 go forward.
See https://github.com/vimeo/psalm/commit/b0f3992f36c048e628b7a326cae77cc876cd67e4.
Apparently `stopOnFirstError` was removed from the configuration options.
=> Remove stopOnFirstError from psalm.xml.

resources/assets/js/app.js
Fixes #1457.
By default, the delay on all tooltips will be 0, which means that as soon as you move your mouse away, the tooltip will disappear.
=> Remove delay on tooltips

.styleci.yml, app/Console/Commands/SendReminders.php, app/Jobs/Notification/ScheduleNotification.php, app/Jobs/Reminder/SendReminderEmail.php, app/Jobs/StayInTouch/ScheduleStayInTouch.php, app/Models/User/User.php, config/app.php, database/migrations/2018_05_20_121028_accept_terms.php, tests/Unit/Jobs/SendReminderEmailTest.php, tests/Unit/Jobs/SendRemindersTest.php, tests/Unit/UserTest.php
This is an attempt to see why, for a small subset of users, reminders are not sent in production. They seem to not even be dispatched.
To help debug, I've added a bunch of logging. Yes it's not pretty - but I have no other way to understand what's happening. We'll remove them once reminders are fixed.
Also, set the instance's timezone to UTC.
=> Refactor how reminders are sent

.env.example, app/Console/Kernel.php, app/Http/Kernel.php, composer.json, composer.lock, config/trustedproxy.php
Trusted proxy permits a request to be recognize as secured.
This is needed for U2F.
These pull request add ability to add proxies from CloudFlare to trusted proxies.
=> Add ability to discover cloudflare trusted proxies automatically

app/Models/Contact/Contact.php, tests/Unit/ContactTest.php
This is related to sentry issue 595752527
=> Fix wrong email used for gravatar

CHANGELOG, CONTRIBUTORS, app/Console/Commands/Update.php
Fixes #1622.
If migrations fail, the storage directory will not be linked to $MONICA_DIR/public/storage, which breaks uploaded avatars. This PR moves the linking command so migrations will be executed at the end.
- [n/a] Screenshots are included if the PR changes the UI.
- [n/a] If you change the UI, make sure the user experience is consistent with the current interface.
- [n/a] Tests added for this feature/bug. - Storage linking was disabled in testing environments before.
- [n/a] Impact on the seeders.
- [n/a] Impact on the API.
- [n/a] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the …
=> Fix missing storage link

CHANGELOG, app/Models/Contact/Contact.php, tests/Unit/ContactTest.php
Add ability to get gravatar, not for the first email, but for every emails: first gravatar detected is returned.
=> feat: Get first existing gravatar of all emails of the contact

CHANGELOG, resources/views/partials/check.blade.php
Avoid displaying "New version available" if current deploy is in advance.
=> fix: fix how comparing version is done

CHANGELOG, app/Http/Requests/SettingsRequest.php
=> fix: fix email maximum size on settings

CHANGELOG, resources/views/emails/reminder/notification.blade.php, resources/views/emails/reminder/reminder.blade.php, resources/views/emails/reminder/stayintouch.blade.php
Fix the link in reminder mails, currently the host appears twice:
=> fix: fix reminder link in email sent

database/migrations/2018_09_05_213507_mark_modules_migrated.php
=> fix: fix duplicated modules on settings page

CHANGELOG, app/Models/Contact/Reminder.php
When we get the next expected date for a reminder, we shouldn't apply a timezone to it. If it Oct 29th, it's Oct 29th, no matter which timezone.
=> fix: fix reminders not showing the right date

app/Http/Controllers/Api/Contact/ApiConversationController.php, app/Http/Controllers/Api/Contact/ApiMessageController.php, app/Services/Contact/Conversation/AddMessageToConversation.php, app/Services/Contact/Conversation/CreateConversation.php, app/Services/Contact/Conversation/DestroyConversation.php, app/Services/Contact/Conversation/DestroyMessage.php, app/Services/Contact/Conversation/UpdateConversation.php, app/Services/Contact/Conversation/UpdateMessage.php, database/seeds/FakeContentTableSeeder.php, tests/Unit/Services/Contact/Conversation/AddMessageToConversationTest.php, tests/Unit/Services/Contact/Conversation/CreateConversationTest.php, tests/Unit/Services/Contact/Conversation/DestroyConversationTest.php, tests/Unit/Services/Contact/Conversation/DestroyMessageTest.php, tests/Unit/Services/Contact/Conversation/UpdateConversationTest.php, tests/Unit/Services/Contact/Conversation/UpdateMessageTest.php
These try/catch are useless. Use the `MissingParameterException` instead of `\Exception` as well.
=> fix: remove useless try catch

CHANGELOG, config/logging.php
We can use papertrail logging by setting `LOG_CHANNEL=papertrail`
=> feat: support papertrail logging

.gitignore, CHANGELOG, app/Console/Commands/Helpers/CommandExecutor.php, app/Console/Commands/SentryRelease.php, app/Console/Commands/SetupTest.php, app/Console/Kernel.php, config/sentry.php, tests/Browser/Settings/MultiFAControllerTest.php
Add a new command to deploy a new release to sentry.
Usage: (example)
`php artisan sentry:release --release=$(php artisan monica:getversion) --environment=production --commit=$(git log --pretty="%H" -n1 HEAD) -vv`
The command will store the 'release' parameter in an new file `.sentry-release` which is then used at runtime (don't forget to run `config:cache` for performances)
This way we can run this command, even if we are not on a git repository (like on fortrabbit ...)
=> feat: add sentry:release command

CHANGELOG, database/migrations/2018_08_31_020908_create_life_events_table.php, database/migrations/2018_10_07_120133_fix_json_column.php
Fix using the type 'json' for a column type, which is available on mysql > 5.7.8 only.
This fix #1882
=> fix: fix use of 'json' column type

readme.md
This is correcting a wrong url on the LICENCE badge in the README.
=> docs(readme): wrong url on LICENCE badge

app/Http/Controllers/Contacts/TasksController.php
events table has been removed in #1829. This line has been missed.
Fix #1922
=> fix: fix task remove after events table removal

app/Models/Contact/Contact.php
Quick fix to show latin initials for non-latin names.
Example:
Example:
=> fix: fix to display non latin names on the dashboard

CHANGELOG, public/changelog.json, resources/views/settings/tags.blade.php
=> feat: add ability to see contacts for each tag in the Tags view on the settings page

app/Console/Commands/Update.php, app/Helpers/ComposerScripts.php, composer.json, composer.lock
Fix composer install problems with the removal of antiflood package
Fix #2023
=> fix: fix composer install problems

resources/views/people/conversations/edit.blade.php
Fixing method errors for editing conversations (#2038) by using the right method in the form.
=> fix: fix editing conversations

resources/views/dashboard/index.blade.php
fixes #2109 
Currently the numerical stats on the dashboard are not spaced out correctly resulting in misaligned stats on desktop and an overflow on mobile. This PR fixes the problem by replacing the previous fixed-width borders with a responsive tachyons grid. The screenshots show the current and new situation:
**Desktop:**
Current:
New:
**Mobile:**
Current:
New:
Pinging @djaiss as this is a UI change.
=> fix: fix dashboard stats spacing

CHANGELOG, app/Http/Controllers/Api/ApiContactTagController.php
This will close #2119 
The problem is that `SetTags` deleted existing tags, which it shouldn't. This method should only add new ones.
=> fix: fix setTag api method which deleted existing tags

resources/views/people/modal/activity_view.blade.php
This changes the class of the contact list `ul` element on the modal activity view to allow clicking names to work as intended (closes #2048).
=> fix: change contact list class to allow following link

CHANGELOG, app/Http/Controllers/CardDAV/CardDAVController.php, app/Models/CardDAV/Backends/MonicaCardDAVBackend.php, app/Models/CardDAV/MonicaAddressBook.php, app/Models/User/SyncToken.php, database/factories/ModelFactory.php, database/migrations/2018_12_29_135516_sync_token.php, tests/Api/Carddav/CarddavContactTest.php, tests/Api/Carddav/CarddavServerTest.php
This implements the [rfc6578](https://tools.ietf.org/html/rfc6578) as describe in [sabre documentation](http://sabre.io/dav/building-a-carddav-client/#speeding-up-sync-with-webdav-sync).
Limitation: this only handles the 'modified' and 'added' contact, but will not senf the 'deleted' ones as a change.
=> feat: carddav: support sync-token

CHANGELOG, app/Models/Contact/Contact.php
=> fix: fix getting birthday reminders about related contacts

CHANGELOG, database/migrations/2019_01_05_202557_add_foreign_keys_to_reminder.php, database/migrations/2019_01_05_202748_add_foreign_key_to_reminder_rule.php, database/migrations/2019_01_05_202938_add_foreign_key_to_contacts.php, database/migrations/2019_01_05_203201_add_foreign_key_for_reminder_in_life-events_table.php, tests/Unit/Models/ReminderRuleTest.php
This is part of a bigger move to add foreign keys everywhere, in order to ensure database consistency.
=> chore: add foreign keys to multiple tables

tests/CreatesApplication.php
This decreases the tests time by 31% on my machine. Thanks to [this tweet](https://twitter.com/taylorotwell/status/943135617466105856?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E943135617466105856&ref_url=https%3A%2F%2Flaravel-news.com%2Ftips-to-speed-up-phpunit-tests).
cc @asbiin
=> chore: reduce the numbers of hashing rounds in CI

CHANGELOG, app/Helpers/DateHelper.php, tests/Unit/Helpers/DateHelperTest.php
Fix parse DateTime in DateHelper.
It allows to use parseDateTime with a compact format like '20190123T080337Z'.
The timezone parameter is not used in any code in Monica.
It's now used to set the timezone of the parsed datetime, but the return value always return an UTC one.
=> fix: fix datehelper parse date

app/Helpers/DateHelper.php, app/Services/VCalendar/ExportTask.php, app/Services/VCalendar/ExportVCalendar.php, app/Services/VCalendar/ImportTask.php, app/Services/VCard/ExportVCard.php, app/Services/VCard/ImportVCard.php, tests/Api/DAV/CardEtag.php, tests/Api/DAV/VCardContactTest.php, tests/Unit/Services/VCard/ExportVCardTest.php
This will fix timestamp handle, and improve vcard, vevent and vtodo export format.
=> fix: fix dav objects import/export

Dockerfile, Makefile, scripts/docker/test-server.sh
Fix feature introduced with #2335
=> fix: fix docker sentry connection

CHANGELOG, app/Http/Controllers/ContactsController.php, app/Models/Contact/Contact.php, app/Notifications/StayInTouchEmail.php, app/Notifications/UserNotified.php, app/Notifications/UserReminded.php, app/Services/VCalendar/ExportTask.php, app/Services/VCalendar/ExportVCalendar.php, app/Services/VCard/ExportVCard.php
- add a function `Contact::getLink` to get the 'people.show' route from either the contact, or the related real contact if the current contact is a partial one.
- use this function in mail templates, DAV export, 
- change of the behavior of `ContactsController::show` in case it's a partial contact, redirect to the related real contact, and not to the 'people.index' route.
This will fix #2232
=> feat: redirect to real contact when it's a partial one

CHANGELOG, app/Helpers/LocaleHelper.php, app/Helpers/VCardHelper.php, app/Models/Contact/Address.php, app/Models/Contact/Contact.php, app/Models/Contact/ContactField.php, app/Models/Contact/ContactFieldType.php, app/Services/VCard/ExportVCard.php, app/Services/VCard/ImportVCard.php, phpstan.neon, tests/Api/DAV/CardEtag.php, tests/Unit/Services/VCard/ImportVCardTest.php
VCard import now parses addresses and contact fields (email and phone) in the same order as on the database, to update, create, and destroy them.
=> fix: fix addresses and contact fields imports on VCard import

composer.json, composer.lock, psalm.xml
Was previously blocked on this because Psalm used a clashing version of `sabre/event` for its language server. It now uses `amphp/amp`, so everything is good.
I'm using the opportunity to write a Laravel plugin - support for that will likely come in a forthcoming PR.
=> ci: upgrade to psalm v3

composer.json, composer.lock
This PR resolves #2534 - `ext-gd` is required by some tests, but is not mentioned in `composer.json`
=> chore(deps): require ext-gd by composer.json

CHANGELOG, app/Helpers/MoneyHelper.php, tests/Unit/Helpers/MoneyHelperTest.php
This PR is related to #2540 
Bug:
`MoneyHelper::format` method is implemented only for two "2" minor unit currencies, and it causes display error for non two "2" minor unit currencies such as JPY, ISK, etc.
Fix:
This PR enables it to format correctly for all minor unit cases which is defined in moneyphp/money lib.
- ~~[ ] If you change the UI, make sure to ask repositories administrators first about your changes by pinging @djaiss or @asbiin in this PR.~~
- ~~[ ] Screenshots are included if the PR changes the UI.~~
- ~~[ ] Front-end tests have been written with Cypress.~~
- ~~[ ] The API has been updated.~~
- ~~[ ] API's documentation has been added by submitting a pull request in the [marketing website repository](https://github.com/monicahq/marketing_site/pulls).~~
- ~~[ ] If you change …
=> fix: money format for non two minor unit currencies

CHANGELOG, resources/views/dashboard/_monthReminder.blade.php
Fixed that the dashboard could crash with "ErrorException: Trying to get property 'contact' of non-object"
Fixes: https://github.com/monicahq/monica/issues/2388
=> fix: dashboard crash when reminder is empty

CHANGELOG, app/Http/Controllers/Contacts/RelationshipsController.php, app/Models/Contact/Contact.php, app/Models/Relationship/Relationship.php, resources/views/people/relationship/_relationship.blade.php, resources/views/people/relationship/edit.blade.php, routes/web.php, tests/Feature/RelationshipTest.php, tests/Unit/Models/ContactTest.php
=> fix: fix display relationship without a ofContact property

docs/installation/generic.md, docs/installation/heroku.md, readme.md
Fix doc instructions about passport
=> docs: fix passport personal access token client creation

app/Http/Controllers/Api/Auth/OAuthController.php
=> refactor: oAuth proxy through HTTP kernel

app/Models/Contact/Contact.php, resources/views/people/_header.blade.php
This commit fixes the Contact Profile page for deceased contacts as noted in #2951. 
Additionally, I fixed a typo in the method that calculates `Age at Death`
=> fix: fix broken age calculation for deceased contacts

CHANGELOG.md, app/Console/Commands/SendStayInTouch.php, app/Jobs/StayInTouch/ScheduleStayInTouch.php, app/Models/Contact/Contact.php, tests/Commands/SendStayInTouchTest.php, tests/Unit/Jobs/ScheduleStayInTouchTest.php, tests/Unit/Models/ContactTest.php
Some times the StayInTouch trigger is missed.
This fix the problem in rescheduling the StayInTouch as it was not previously missed.
=> fix: reschedule missed stay-in-touch

CHANGELOG.md, app/Traits/Searchable.php
Fix this error:
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'account_id' in where clause is ambiguous (SQL: select count(*) as aggregate from `contacts` left join `activity_contact` on `contacts`.`id` = `activity_contact`.`contact_id` left join `activities` on `activity_contact`.`activity_id` = `activities`.`id` where `contacts`.`account_id` = XXX and `contacts`.`account_id` is not null and `is_partial` = 0 and `is_active` = 1 and `is_dead` = 0 and account_id = XXX and (first_name LIKE '%%' or middle_name LIKE '%%' or last_name LIKE '%%' or nickname LIKE '%%' or description LIKE '%%' or job LIKE '%%')) ```
=> fix: fix scope search

CHANGELOG.md, app/Console/Commands/Clean.php
Remove confirmation trait to able the command to actually run on scheduling.
=> fix: remove monica:clean command confirmation

CHANGELOG.md, app.json, config/database.php
Change the default mysql instance type on heroku, to create a mysql 5.7 instance (ClearDB uses mysql 5.6 by default).
This will let users create an instance with the right mysql version on heroku.
See #2926 or #2761 too.
=> feat: use JawsDB by default on heroku instances

CHANGELOG.md, resources/views/people/_header.blade.php
This adds the job information next to the contact name if it’s defined on the profile page.
If you care enough to fill this information on a contact, it means it’s important to you when you take a look at the contact. Therefore, it makes sense to display it on the profile page.
Close #3143
=> feat: add job information next to the contact name on profile page

.platform.app.yaml
Updates .platform.app.yaml - adding app/temp as writable directory under `mounts`.
=> fix: update .platform.app.yaml - add app/temp to writable mounts

docs/installation/docker.md
The `:fpm` tag was missing from the docker-compose example.
=> docs: Missing fpm tag in docker-compose example

app/Http/Resources/Contact/ContactWithContactFields.php
This PR adds the latest 3 notes that the user has written about a contact in the `/contact/{id}?with=contactfields` API method.
The reason I had this info only in this call is that this call will be used in the mobile app to reduce the number of queries we have to do to display a contact.
=> chore: add notes in contact api call

app/Services/Contact/Description/ClearPersonalDescription.php, app/Services/Contact/Description/SetPersonalDescription.php, tests/Unit/Services/Contact/Description/ClearPersonalDescriptionTest.php, tests/Unit/Services/Contact/Description/SetPersonalDescriptionTest.php
This PR adds two new services:
* one to set the contact's personal description
* the other one to clear the personal description.
Both services will be needed for the new UI.
=> feat: services to set and clear personal description

app/Http/Controllers/Api/ApiContactController.php, app/Http/Controllers/ContactsController.php, app/Jobs/UpdateLastConsultedDate.php, tests/Unit/Jobs/UpdateLastConsultedDateTest.php
The `contact->updateConsulted()` method is now done in a job, instead of being a method called on the Contact object.
First of all, it’s better to put this kind of operations in a job (instead of blocking the main thread for this), and also, I’ll need this in a job for the new UI 😀
cc @asbiin
=> chore: last consulted at field update is now in a job

app/Http/Controllers/Contacts/DebtController.php, app/Http/Controllers/Contacts/RemindersController.php, app/Http/Controllers/SettingsController.php
Fix error related to #3570
[`_header`](https://github.com/monicahq/monica/pull/3570/files#diff-345a977fab59890c36e33431012dafae) template requires a `$accountHasLimitations` variable, but this template is included in other blade templates.
=> fix: fix _header blade include

docs/installation/heroku.md
Update heroku.md to use an updated second screenshot to reflect switch to JawsDB (from ClearDB) as Monica's default database provider in Heroku.
=> docs: Update heroku docs to use updated screenshot

.github/workflows/cypress.yml, CHANGELOG.md, app/Http/Controllers/DAV/Backend/SyncDAVBackend.php, tests/Api/DAV/CalDAVBirthdaysTest.php, tests/Api/DAV/CalDAVTasksTest.php, tests/Api/DAV/CardDAVTest.php
See https://tools.ietf.org/html/rfc6578#section-4
=> fix: fix carddav sync-collection reporting wrong syncToken

.github/workflows/cypress.yml
Do not run github action on crowdin branch
=> chore: ignore cypress on crowdin branch

CHANGELOG.md, scripts/docker/apache/Dockerfile
=> fix: fix docker cron (legacy) on apache variant

CHANGELOG.md, app/Http/Middleware/AuthenticateWithTokenOnBasicAuth.php
This authentication is not 100% secure, and it can bypass 2fa.
From now, authentication for carddav must use API Token.
Use login + Token, or just the token on your carddav app.
Fix  #3829
=> feat: remove authentication with login + password for carddav

CHANGELOG.md, config/filesystems.php
Add [cache](https://laravel.com/docs/7.x/filesystem#caching) to S3 storage. This will improve metadata gets.
Also use [standard variables](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L60):
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_DEFAULT_REGION
- AWS_ENDPOINT
of course old environment variables are still working.
=> feat: add cache for S3 storage, and use new standard variables

routes/web.php
In AbstractRouteCollection.php line 210:
[LogicException]
Unable to prepare route [tasks] for serialization. Another route has already been assigned name [people.tasks.index].
=> fix: fix route cache

docs/installation/providers/cloudron.md
We recently changed our demo instance URL to https://my.demo.cloudron.io
=> docs: fix cloudron link to demo instance

CHANGELOG.md, resources/views/people/relationship/_relationship.blade.php
Fix #3989
added age of death to relationships sidebar for all relationships that are marked as deceased.
if not marked as deceased, it will proceed as normal to calculate the age of the person.
=> feat: add age of death to relationship sidebar if the person is dead

docs/installation/providers/ubuntu.md
I had to install `apache2` first on Ubuntu 18.0.4. Without doing so, the directory `/var/www` did not exist and I could not follow the installation steps.
=> docs: update ubuntu.md

docs/installation/providers/ubuntu.md
default install with dashboard doesn't run without php-imagick and shows an error. Solves #4644
=> docs: update ubuntu.md to add php-imagick dependency

app.json, docs/installation/providers/heroku.md
This should make it easier for people using Heroku for their emails to link to their app instead of the default URL ([http://localhost](https://github.com/monicahq/monica/blob/10f7f197309112836f39279de27e82ae5270ed4f/config/app.php#L66)).
=> docs: add APP_URL to Heroku template

CHANGELOG.md, app/Helpers/AccountHelper.php, tests/Unit/Helpers/AccountHelperTest.php
This PR
💁‍♂️  It's not 1920 anymore.
=> feat: default gender to unknown

app/Services/Contact/Avatar/GetAdorableAvatarURL.php, database/migrations/2021_01_10_235600_update_adorable_api.php, tests/Unit/Services/Contact/Avatar/GetAdorableAvatarTest.php
Resolves https://github.com/monicahq/monica/issues/4777
The Adorable.io avatar API has been closed down: https://github.com/itsthatguy/avatars-api-middleware/issues/108#issuecomment-709611542
This PR switches the URL to https://api.hello-avatar.com/adorables/ to immediately get the avatars working again.
See: https://github.com/itsthatguy/avatars-api-middleware/issues/108#issuecomment-709593363
=> fix: update adorable api to api.hello-avatar.com

README.md, composer.json, composer.lock, docs/contribute/readme.md, docs/installation/providers/cpanel.md, docs/installation/providers/debian.md, docs/installation/providers/generic.md, docs/installation/providers/ubuntu.md, docs/installation/readme.md, scripts/docker/Dockerfile, scripts/vagrant/build/install-monica.sh
PHP 7.3 now accepts only security fixes, and PHP 7.4 is fully supported.
See https://www.php.net/supported-versions.php
=> refactor: change minimum php version for 7.4

app/Http/Controllers/Api/ApiContactController.php, app/Http/Controllers/Contacts/ContactAuditLogController.php, app/Http/Controllers/Contacts/RelationshipsController.php, app/Http/Controllers/ContactsController.php, app/Services/Contact/Contact/UpdateContact.php, app/Services/Contact/Description/SetPersonalDescription.php, app/ViewHelpers/ContactHelper.php, tests/Feature/RelationshipTest.php, tests/Unit/Services/Contact/Contact/UpdateContactTest.php
It didn't work before, now it does.
It also appears on the Audit log in the Settings.
=> feat: set and clear personal description now appears in change log

app/Helpers/InstanceHelper.php, app/Http/Controllers/Settings/SubscriptionsController.php
This fix #4951 
`InstanceHelper::getPlanInformationFromConfig` need the friendly name, and not the PlanId - to be fair, I don't know how it worked before ...
=> fix: fix subscriptions list display

.env.example, app/Http/Controllers/Api/Auth/OAuthController.php, config/passport.php, docs/installation/providers/generic.md, docs/installation/providers/heroku.md, tests/Browser/Auth/AuthControllerTest.php
There was a mistake between 
- [Personal access token](https://laravel.com/docs/8.x/passport#personal-access-tokens), used to provide personal access token
- [Password grant token](https://laravel.com/docs/8.x/passport#password-grant-tokens), used to register an oauth application
A confusion has been made in the passport config between these 2.
The `PASSPORT_PERSONAL_ACCESS_CLIENT_ID` and `PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET` environment variable are optional to set.
`PASSPORT_PASSWORD_GRANT_CLIENT_ID` and `PASSPORT_PASSWORD_GRANT_CLIENT_SECRET` are only useful if you want to activate oauth client login.
This fix it.
=> refactor: distinguish passport password client and personal access token client configuration

.github/workflows/deploy.yml
Add `.version` file in deployment
=> fix: fix deploy on fortrabbit with version number

.github/workflows/build.yml, .github/workflows/cypress.yml, .github/workflows/deploy.yml, .github/workflows/migration_tests.yml, .github/workflows/release.yml, .github/workflows/static.yml, .github/workflows/tests.yml, .platform.app.yaml, composer.json, composer.lock, config/google2fa.php, docs/installation/providers/cpanel.md, docs/installation/providers/debian.md, docs/installation/providers/generic.md, docs/installation/providers/ubuntu.md, resources/js/components/settings/MfaActivate.vue, scripts/docker/Dockerfile, scripts/vagrant/build/install-monica.sh
Get rid of imagick, it's not supported everywhere, and there is no php 8.0 version.
QrCode will now be rendered with svg.
=> refactor: remove imagick dependency

app/Console/Commands/ImportVCards.php, app/Http/Controllers/Auth/InvitationController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/SettingsController.php, app/Jobs/GetGPSCoordinate.php, app/Jobs/SendNewUserAlert.php, app/Providers/AppServiceProvider.php, app/Services/Account/Place/CreatePlace.php, app/Services/Account/Place/UpdatePlace.php, app/Services/Instance/Geolocalization/GetGPSCoordinate.php, app/Services/Instance/Weather/GetWeatherInformation.php, tests/Feature/ExportAccountAsSQLTest.php, tests/Feature/RegisterTest.php, tests/Unit/Jobs/ScheduleStayInTouchTest.php, tests/Unit/Jobs/UpdateLastConsultedDateTest.php, tests/Unit/Models/ContactTest.php, tests/Unit/Services/Account/Place/CreatePlaceTest.php, tests/Unit/Services/Account/Place/UpdatePlaceTest.php, tests/Unit/Services/Instance/Geolocalization/GetGPSCoordinateTest.php, tests/Unit/Services/Instance/Weather/GetWeatherInformationTest.php
This adds a RateLimiter for get coordinates queries, using [Laravel RateLimiter](https://laravel.com/docs/8.x/queues#rate-limiting)
Also use Http facade to call apis.
=> feat: add a rate limiter for locationiq queries

README.md
Prior versions worked because yarn assets were pre-built and included.  With the removal of these, I don't think Monica can be successfully updated on a machine with 768MB or less of RAM.  I *think* yarn's memory requirements are too high.
Monica had been working fine on a Debian VPS with 256MB RAM.  It was a little slow but fully functional.  While trying to upgrade to 3.0, I could not successfully run the `yarn run production` command.  Despite being left for 6+ hours on several attempts, it simply freezes and does not go any further during the "fetching packages" stage.
I tried to build 3.0 on another Debian VPS with 768MB of RAM.  It got further in the process but repeatedly failed with this error:
error Command failed with exit code 134
Which, as far as I can tell from Google, is …
=> docs: Revised minimum hardware requirements due to build process

app/Helpers/SearchHelper.php, app/Models/Contact/Contact.php, tests/Unit/Helpers/SearchHelperTest.php
This adds support for searching through notes [as explained here](https://github.com/monicahq/monica/issues/5079). There are already tests for the contact search helper, but let me know if you feel like this functionality needs a dedicated test.
=> feat: search notes when searching through contacts

tests/Feature/RegisterTest.php
As discussed in https://github.com/monicahq/monica/pull/5097
=> fix: adding missing configuration required for tests to pass locally

docs/installation/providers/debian.md
1. curl is not installed by default on Debian 10 (not sure about previous version), so use `wget` instead
2. PHP 7.4 is not available on Debian <=10 (only available in testing/unstable), instead use deb.sury.org packages (from the maintainer of the Debian packages.)
3. Composer v1 is the only available version on Debian <=10, install from getcomposer.org to get v2
Doing this allowed me to get Monica running locally on a clean Debian 10 netinst.  The hardest part was getting php 7.4 installed, apt kept wanting to install php8 and I didn't know if that was supported.
=> docs: update debian instructions to support deb10

app/Helpers/SearchHelper.php, tests/Unit/Helpers/SearchHelperTest.php
This is a temporary fix for #5103 which caused a lot of performance issues in production, considering the size of the database.
=> fix: fix search being extremely slow

app/Http/Controllers/Auth/InvitationController.php, app/Http/Controllers/Auth/PasswordChangeController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/ResetPasswordController.php, app/Http/Requests/PasswordChangeRequest.php, app/Listeners/LogoutUserDevices.php, app/Providers/AppServiceProvider.php, app/Providers/EventServiceProvider.php
This fix #5270
However, session removal is only working when session is handled by database, i.e. `SESSION_DRIVER=database`
=> feat: revoke session from other browser after a password change

docs/contribute/docker.md, scripts/docker/Dockerfile
The individual copy commands missed some key files that are required to build the image. I don't see any downside to copying the entire source over.
=> Fixing local docker development

.env.example, config/filesystems.php
Hello,
I have added path style URL support to Monica by adding a single line relying on a new `S3_PATH_STYLE` environment variable, kept to false by default as to not have any impact whatsoever if left unconfigured of course. This was already supported by the underlying S3 library so the edit was quite trivial.
This is necessary for a lot of people depending on e.g. self-hosted MinIO setups, where virtual-hosted style URLs may not be enabled or supported. This was my case so after a bit of research, I found and added this option. I believe it can help others and won't impact anyone who doesn't explicitly set this to true so… may as well PR it!
=> feat: add path style URL support for S3 buckets

resources/lang/en/settings.php
It's the definition used here: https://en.wikipedia.org/wiki/Brazilian_Portuguese
=> style: rename pt-BR to Brazilian Portuguese

CONTRIBUTORS, resources/views/people/profile.blade.php
Fix bug where the contacts name is not populating the delete confirmation
Resolves: https://github.com/monicahq/monica/issues/5412
=> fix: Contact name population on delete confirmation

CONTRIBUTING.md
The README.md link seems to be case sensitiv at github, so i fixed it.
Before:
=> docs: fix case-sensitive readme-link in contributing.md

CONTRIBUTORS, resources/js/components/people/activity/ActivityList.vue, resources/lang/en/people.php
Feat / Fix: #4204 
Adds total of participants in activities. See below for the screenshot.
I reduced the total by one, because in the array also the contact itself is indicated, but not in the displayed list.
=> feat: add total of participants in activity

app/Http/Controllers/ContactsController.php, resources/js/components/people/StayInTouch.vue, resources/lang/en/people.php
Fix #5158 
The screenshot of this feature:
I had to change the ContactController stayInTouch function because I needed the new calculated next reminder date when I update the frequency of the reminder.
Otherwise I'ld have needed to make a second request to the API.
=> feat: add next reminder date to stayintouch

README.md
The build badge in the README file was still pointing to an outdated Azure build run from February.
Seems like builds have been migrated to GitHub Actions afterwards.
I used the `tests` workflow, since that seems to be the correct one to replace a *whole* build flow.
=> docs: update build badge in README

resources/views/layouts/skeleton.blade.php
This makes changes the status bar and over scroll areas to Monica’s dark blue on recent iOS and Android devices.  There’s a good [write-up of it here](https://stuffandnonsense.co.uk/blog/time-to-update-your-theme-color-meta-tag-for-safari).
I’ve also grouped the `meta` tags together, to be more consistent with the other tags in the `head` area which were also grouped by type.
=> style: Added theme-color meta tag

docs/installation/update.md, scripts/update/debian.sh
This is very much a “use at your own risk”, but it’s a tidied-up version of what I use to update Monica on Debian.  It’s worked successfully for me for several versions now.
It’s got several mitigations in place to address the wonkiness and brittleness I discussed #5510.  Specifically, it deletes all the composer and node modules before reinstalling them.  I’ve found that doing this is often the only way to successfully update Monica – it breaks mid-update otherwise.
=> feat: Debian update script (closes #5567)

docs/contribute/docker.md
By default, docker-compose expect a `docker-compose.yaml` or `docker-compose.yml` file. If missing, this lead to the following error : 
```
$ docker-compose build
ERROR: 
Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?
Supported filenames: docker-compose.yml, docker-compose.yaml
```
=> fix(docs): specify docker-compose.dev.yaml argument

app/Http/Controllers/Api/ApiReminderController.php, app/Http/Resources/Reminder/ReminderOutbox.php, routes/api.php, tests/Api/ApiReminderControllerTest.php
Close #5778 
Docs close monicahq/marketing_site#642
1. Get upcoming reminders for `current month`
```
GET /api/reminders/upcoming
```
or
```
GET /api/reminders/upcoming/0
```
2. Get upcoming reminders for `next month` (`month+1`)
```
GET /api/reminders/upcoming/1
```
3.  Get upcoming reminders for `next n month` (`month+n`)
```
GET /api/reminders/upcoming/n
```
=> feat: add `reminders/upcoming` API

app/Http/Middleware/CheckVersion.php, resources/views/partials/check.blade.php, resources/views/partials/footer.blade.php
=> fix: version display on heroku

app/Helpers/AccountHelper.php, app/Jobs/Reminder/NotifyUserAboutReminder.php, resources/views/dashboard/_monthReminder.blade.php, tests/Unit/Jobs/Reminder/NotifyUserAboutReminderTest.php
Fix #5912 
This is due to the recent soft delete contacts: when a contact is (soft) deleted, the reminder is still there, and it brokes the dashboard.
=> fix: fix month reminder view

app/Http/Controllers/Api/ApiContactController.php, app/Http/Controllers/Api/ApiMeController.php, app/Http/Controllers/Contacts/ActivitiesController.php, app/Http/Controllers/MeController.php, app/Notifications/NewUserAlert.php, resources/js/components/people/MeContact.vue, resources/js/components/people/activity/ActivityList.vue, resources/js/components/people/activity/CreateActivity.vue, resources/js/components/people/gifts/CreateGift.vue, resources/js/components/people/photo/PhotoList.vue, resources/js/components/people/photo/PhotoUpload.vue, routes/api.php, routes/web.php, tests/Api/Contact/ApiContactControllerTest.php, tests/Api/Contact/ApiMeControllerTest.php, tests/Feature/ActivityTest.php, tests/Feature/MeTest.php
This removes all api call in vue.
It will remove the necessity of creating oauth keys on a deployment to make UI works.
This fix #6000
=> refactor: remove api call in vue

app/Http/Controllers/Contacts/TasksController.php
Fixes #6023
Currently the code crashes if a contact has a non-completed task, as DateHelper::getShortDate requires a non-null Carbon object. 
This PR allows the completed_at value to be null without a crash.
=> fix: 6023 Allow empty completed_at task date

resources/sass/modal.scss
Fixes #5817
Some modals are spawned in Vue with the help of the sweet-modal-vue package. 
This package uses the "-webkit-perspective" CSS property which leads to blurry text while not being useful in the use-case of Monica. 
This PR removes disables this property and restores sharp text in modals. 
I wasn't too sure where to put the fix, don't hesitate to ask me to move it to a better file.
=> fix: 5817 blurry modals from sweet-modal-vue

resources/js/components/journal/JournalList.vue
Fixes #5906
The journal sidebar was not responsive
Before : 
After :
=> fix: 5906 Journal sidebar width on mobile

resources/js/components/people/activity/ActivityList.vue
Feature for #4190
Added the "Load More" option in the activities. Now users can see more than 15 entries of their activities.
=> feat: 4190 load more activities

resources/js/components/people/lifeevent/CreateLifeEvent.vue
This is a JS problem, current version sends this on create:
```
happened_at	"2022-0-0"
happened_at_day_unknown	false
happened_at_month_unknown	false
```
Whereas old version sent this:
```
happened_at	"2022-1-1"
happened_at_day_unknown	true
happened_at_month_unknown	true
```
This issue was introduced by 57b31f6526e3628cc98c8c271108bc34dd2d074e
The strict comparison added in the `updateDate` function in CreateLifeEvent.vue broke it.
The values for `this.selectedMonth` and `this.selectedDay` can be numbers/integers or strings, depending on where they come from.
Initial values and values set by JS are numbers, whereas values set by user input are strings.
Fixes #5936
I guess there might be a nicer approach to this in vue, or in general, though I don't have an idea :)
=> fix: life event creation with unknown month/day

docs/installation/providers/debian.md, docs/installation/providers/generic.md
A few weeks ago, @aaronpk updated the Ubuntu installation doc in PR #5980 to note that Node.js 16 is now the minimum required version, but forgot to update the Debian and Generic docs with the same change. This PR simply updates those two docs.
Issue #6048 was recently opened pointing out this issue on Debian, so this PR solves that issue.
=> docs: node 16 in debian and generic

app/Services/VCard/ExportVCard.php, tests/Unit/Services/VCard/ExportVCardTest.php
Fix #6079 
The vCard export is incorrect when the year is unknown.
It exported the birthday like:
`--mm-dd`
.. but it should be:
`--mmdd`
Referring to https://datatracker.ietf.org/doc/html/rfc6350/#section-6.2.5
Added test and fix.
=> fix: vcard bday export format with unknown year

CONTRIBUTORS, config/app.php
This pull request fixes the issue mentioned in #5954, which was wrongfully closed after the merge of #5955. It also fixes #6024
=> fix: change APP_TRUST_PROXIES to APP_TRUSTED_PROXIES 

app/Http/Controllers/DAV/Backend/CardDAV/CardDAVBackend.php
fixes #5150
Adds the real scope to the carddav sync query so that non-real contacts are not included.
=> fix: only include real contacts in carddav sync

.github/workflows/build.yml, .github/workflows/cypress.yml, .github/workflows/deploy.yml, .github/workflows/docker.yml, .github/workflows/migration_tests.yml, .github/workflows/release.yml, .github/workflows/static.yml, .github/workflows/tests.yml, .platform.app.yaml, README.md, composer.json, composer.lock, docs/contribute/readme.md, docs/installation/providers/cpanel.md, docs/installation/providers/debian.md, docs/installation/providers/generic.md, docs/installation/providers/ubuntu.md, docs/installation/readme.md, template-definition.yaml
We need to switch to php 8.0+ for dependencies reason. We rely on multiple packages, and many of their recent versions require php 8.0+ now.
We'll keep 8.0 as a minimum for now, but we may switch to php 8.1 sooner or later...
=> feat!: drop php 7.4 support

scripts/docker/Dockerfile
When I tried to run `docker-compose -f docker-compose.dev.yml up -d`  it failed with composer error.
It required PHP 8.1, I found that Dockerfile is using the PHP version 8 and composer is set with dependency on 8.1
I changed this in Dockerfile to make it work.
=> fix: update php version in Dockerfile

composer.json, composer.lock, phpstan.neon
This PR upgrades the `nunomaduro/larastan` dependency to the latest version. Which gets rid of an ignored error.
=> chore: upgrade Larastan

resources/js/components/people/Tags.vue
When adding or editing tags, input box now automatically receives focus so that the process of adding tags is one click smoother.
fixes #5979
=> feat: focus tags input box

app/Console/Kernel.php, app/Domains/Contact/Dav/Jobs/UpdateVCard.php, app/Domains/Contact/Dav/Web/Backend/CardDAV/CardDAVBackend.php, app/Domains/Contact/DavClient/Jobs/DeleteLocalVCard.php, app/Domains/Contact/DavClient/Jobs/DeleteMultipleVCard.php, app/Domains/Contact/DavClient/Jobs/DeleteVCard.php, app/Domains/Contact/DavClient/Jobs/GetMultipleVCard.php, app/Domains/Contact/DavClient/Jobs/GetVCard.php, app/Domains/Contact/DavClient/Jobs/PushVCard.php, app/Domains/Contact/DavClient/Jobs/SynchronizeAddressBooks.php, app/Domains/Contact/DavClient/Services/SynchronizeAddressBook.php, app/Domains/Contact/DavClient/Services/Utils/AddressBookGetter.php, app/Domains/Contact/DavClient/Services/Utils/AddressBookSynchronizer.php, app/Domains/Contact/DavClient/Services/Utils/Dav/DavClient.php, app/Domains/Contact/DavClient/Services/Utils/PrepareJobsContactPushMissed.php, app/Domains/Contact/DavClient/Services/Utils/PrepareJobsContactUpdater.php, app/Logging/CleanLogs.php, app/Logging/Loggable.php, app/Logging/LoggingHandler.php, app/Models/AddressBookSubscription.php, app/Models/Log.php, config/logging.php, database/migrations/2023_07_03_230200_create_addressbook_subscription.php, database/migrations/2023_08_30_202650_create_logs_table.php, database/migrations/2023_08_30_202650_fix_addressbook_currentlogid.php, phpstan.neon, tests/Unit/Domains/Contact/DavClient/Jobs/DeleteLocalVCardTest.php, tests/Unit/Domains/Contact/DavClient/Jobs/DeleteMultipleVCardTest.php, tests/Unit/Domains/Contact/DavClient/Services/Utils/PrepareJobsContactUpdaterTest.php
This creates a log mechanism to get logs for Carddav client activities.
The logs are stored in database, and uses laravel `Log` interface.
=> feat: add logs for addressbook subscriptions

app/Domains/Contact/ManageQuickFacts/Web/ViewHelpers/ContactModuleQuickFactViewHelper.php, resources/js/Shared/Modules/QuickFacts.vue, tests/Unit/Domains/Contact/ManageQuickFacts/Web/ViewHelpers/ContactModuleQuickFactViewHelperTest.php
=> fix: fix quick facts not being able to be saved

app/Services/BaseService.php
When value is empty string, it's caught in empty check condition and return null.
So suggest removing useless condition.
```
$val = '';
var_dump(empty($val)); // true
var_dump($val == '');  // true
```
=> refactor: remove useless condition

app/Console/Commands/Local/MonicaLocalize.php, app/Domains/Settings/ManageNotificationChannels/Services/CreateUserNotificationChannel.php, app/Exceptions/EmailAlreadyExistException.php, app/Listeners/WebauthnRegistered.php, tests/Unit/Domains/Settings/ManageNotificationChannels/Services/CreateUserNotificationChannelTest.php
The `EmailAlreadyExistException` is not displayed to the user
=> refactor: handle user notification validation

database/migrations/2017_01_28_222114_remove_viewed_at_from_contacts.php
=> fix: migration 2017_01_28_222114_remove_viewed_at_from_contacts

composer.json, docs/installation/providers/cpanel.md, docs/installation/providers/debian.md, docs/installation/providers/generic.md
This PR adds the php tokenizer extension as a dependency in composer.json, which will prevent user from suffering unexpected consequences such as the cryptic error message in #6469 
Composer will now warn on install  that the extension is needed. Also, the installations docs have been updated to document this dependency.
Closes #6524 and #6469
=> docs: refers missing php tokenizer dependency

app/Models/Contact/Contact.php, app/Models/User/User.php, resources/lang/en/settings.php, tests/Unit/Models/ContactTest.php
This fixes #6285.
Where nicknames are used as diminutives of full first names, it (hopefuly) makes sense to indicate as such in both the full name and short name fields.
=> feat: add a name order with the last name outside of brackets

app/Http/Controllers/JournalController.php, resources/js/components/journal/partials/JournalContentRate.vue, routes/web.php
Hi,
this Pull Request in response to Issue #6051 ,This PR aims to solve the problem by introducing an edit option for the daily journal feature.
Thanks
PART OF GTC OPEN SOURCE INTIATIVE
=> feat: edit Option For Daily Journal

app/Http/Controllers/JournalController.php, resources/js/components/journal/JournalList.vue, resources/lang/ar/journal.php, resources/lang/cs/journal.php, resources/lang/da/journal.php, resources/lang/de/journal.php, resources/lang/el/journal.php, resources/lang/en-GB/journal.php, resources/lang/en/journal.php, resources/lang/es/journal.php, resources/lang/fa/journal.php, resources/lang/fi/journal.php, resources/lang/fr/journal.php, resources/lang/he/journal.php, resources/lang/hr/journal.php, resources/lang/id/journal.php, resources/lang/it/journal.php, resources/lang/ja/journal.php, resources/lang/nl/journal.php, resources/lang/no/journal.php, resources/lang/pt-BR/journal.php, resources/lang/pt/journal.php, resources/lang/ru/journal.php, resources/lang/sv/journal.php, resources/lang/tr/journal.php, resources/lang/uk/journal.php, resources/lang/vi/journal.php, resources/lang/zh-TW/journal.php, resources/lang/zh/journal.php
Based on Issue #6445 , it appears that users are facing difficulties accessing older activities in the application.
In my pull request, I have proposed a solution by introducing a filter that allows users to navigate and access older activities in the journal. This enhancement would greatly improve the user experience by providing a means to conveniently access older activities that may have been missed or require modifications.
Thanks.
PART OF GTC OPEN SOURCE INTIATIVE
=> feat: Add filter to journal

resources/js/Shared/Form/TextArea.vue
Close #6780 
Character count now appears above the textarea.
=> chore: move character count on textarea

config/database.php
Hi there,
I tried to use Redis as a cache / queue manager and I am facing this error:
`Redis::connect(): Argument #2 ($port) must be of type int, string given`
Seems like it can be easily fixed by casting value into an int value. see:
https://github.com/laravel/framework/issues/36693
=> fix(config): cast redis port into int

.github/ISSUE_TEMPLATE/bug_report.yml
While creating a bug report, I've noticed a small typo in a description field
=> docs(typo): update description with product name

app/Models/MultiAvatar.php
I've changed the return in line 29, of function  __invoke($avatarId, $sansEnv, $ver), which returned a variable that had been assigned to a value on the previous line, so that the returns gives the value directly
=> refactor: Update MultiAvatar.php, solving a SonarCloud bug

app/Domains/Contact/ManageContact/Services/MoveContactToAnotherVault.php, tests/Unit/Domains/Contact/ManageContact/Services/MoveContactToAnotherVaultTest.php
Fix #7102 
With this PR, when moving a contact, if the contact belongs to a company:
- if the company has only this contact, we move the the company to the new vault
- if the company has more than this contact, we create a new company to the vault, with the exact same information.
=> fix: fix company not moving when moving a contact

database/migrations/2025_07_06_200000_fix_synctokens.php
Update the foreign key constraint for `sync_token_id` in the `addressbook_subscriptions` table to reference the `sync_tokens` table, ensuring proper handling of deletions.
=> fix: Fix sync token foreign key relationship in addressbook subscriptions (again)

config/scout.php
Add the properties `first_name` and `last_name` to the `sortableAttributes` for meilisearch.
Should fix: https://github.com/monicahq/monica/issues/7764
=> fix: add first_name and last_name to sortableAttributes
